### ISSUE TITLE
AltTesterPrefab remains in hierarchy after closing app

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1017]
## Steps to reproduce
Start instrumented app in Unity Editor. Observe how AltTesterPrefab is inserted in the hierarchy. Stop the app.

## Actual result

AltTesterPrefab does not get erased.

## Expected result

The prefab should be deleted from the hierarchy after closing the app.

**Comment by iulianatodoran** [comment]
### Testing Environment
- OS: Windows 10/ macOS Big Sur v 11.6.8/ Android 12/ iOS 12.5.5
- Unity v 2021.3.15f1 (Windows) and v 2021.3.5f1 (Mac)
- AltTester Unity SDK v 1.8.1 (alpha)- latest from `development` branch in 14.12.22

### Tests performed and results
- :heavy_check_mark: Checked in Unity that after stopping the instrumented app from the _AltTester Editor_ the `AltTesterPrefab` is deleted
- :heavy_check_mark: Checked that after restarting the instrumented app from the _AltTester Editor_ the `AltTesterPrefa`b is present in the Hierarchy of unity objects

### Conclusions
The purpose of this ticket was achieved.
Closing the ticket.
