### ISSUE TITLE
Change the assert condition for TestPressKeyWaitTheDuration

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1026]
## Steps to reproduce
 

The test should pass only when the duration that is read is equal or a little bigger that the duration of the command
For example if in test the command duration is 1 second then is ok if the value returned is [1,1.1] larger or smaller value should fail the test.

Smaller value that 1 shouldn't happen at all but larger that 1.1 might happen if the game is running slowly(low FPS)

**Comment by andreion1ca** [comment]
Moving the issue in **TODO** in order to can be taken by someone else.

**Comment by iulianatodoran** [comment]
### Testing Environment
- OS for Unity: `Windows 11`, `MacOS Big Sur v 11.7.4`
- instrumented builds created in Unity version `2021.3.16f1 LTS`
- _Samplescenes_ game instrumented with AltTester Unity SDK from `development` branch in 06.03.2023
- game tested on devices with OS: `Android 11`, `iOS 12.5.6`, `Windows 11`,` MacOS Big Sur v 11.7.4`

### Problems found during testing
- 🚫 Ran `TestPressKeyWaitTheDuration` multiple times on iOS, Android, MacOS and Windows builds and the test fails at some point with an error of type: `Expected: greater than or equal to 1.0f  But was:  0.998347282f`
  - also another error was present in the unity console after the one mentioned above: 
```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <75633565436c42f0a6426b33f0132ade>:0)
AltTesterEditor.AltTestRunner.setTestStatus (NUnit.Framework.Interfaces.ITestResult test) (at Assets/AltTester/Editor/AltTestRunner.cs:317)
AltTesterEditor.AltTestRunner+<>c__DisplayClass7_0.<RunTests>b__0 () (at Assets/AltTester/Editor/AltTestRunner.cs:54)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <75633565436c42f0a6426b33f0132ade>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <75633565436c42f0a6426b33f0132ade>:0)
```
Screenshot
![image](https://user-images.githubusercontent.com/62327834/223154116-47b740fb-8eb3-4f61-828a-d5b20ad45e40.png)

### Note
- To run the test multiple times used the `[Repeat(x)]` attribute for the test

@SandyEma9 This aspect should be investigated and if the case will reopen the ticket (cc @sandraaltom)

**Comment by iulianatodoran** [comment]
### Clarification
The issue mentioned in my previous comment seems to be inside the `PressKey` command and not in the test itself, so will open another ticket for the command.

### Conclusion
**Closing this ticket.**
