### ISSUE TITLE
Projects using only the old IS have errors because of the NIS when importing the Tester

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1028]
## Steps to reproduce
Import AltTester in a project using only OIS.

## Actual result

A list of errors appears.

### Additional info
Issue was reported on Discord: https://discord.com/channels/744769398023127102/748145712100933682/1052804013701222400

## Expected result

No errors.

**Comment by prohorsex** [comment]
Same problem.

**Comment by sandraaltom** [comment]
Triaged Week no. 39, 2023. 
This issue was fixed.
