### ISSUE TITLE
Add logs to WebGL

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1029]
Saving logs to file was the problem why we couldn't make a build for newer versions of Unity than 2019. Logs are now displayed in the browser's console. 
Target: find a way of saving logs to file.

**Comment by iulianatodoran** [comment]
✔️ Checked on the repository documentation on the `feature-proxy` branch that the section for _Logging in WebGL_ was added with correct and complete information for the way of saving logs to a file.

The purpose of the ticket was achieved.

**Closing the ticket.**
