### ISSUE TITLE
Add a getAltDriver tests helper for Java

### ISSUE THREAD

**Issue by robert-altom** [alttester/AltTester-Unity-SDK#1031]
Add a `getAltDriver` test helper for the Java tests, that will create and return a new `AltDriver` object.  

Update all tests cases to use the `getAltDriver` test helper instead of creating a new `AltDriver` object. 

The goal is to make it easier to update the Java tests, for example to update the timeout or the game name for all tests in one place instead of needing to update all test cases.

**Comment by AlexMitDemBart** [comment]
@robert-altom i could take this.

**Comment by AlexMitDemBart** [comment]
pull request is open https://github.com/alttester/AltTester-Unity-SDK/pull/1034
