### ISSUE TITLE
Add a GetAltDriver tests helper for C#

### ISSUE THREAD

**Issue by robert-altom** [alttester/AltTester-Unity-SDK#1032]
Add a `GetAltDriver` test helper for the C# tests, that will create and return a new `AltDriver` object.  

Update all tests cases to use the `GetAltDriver` test helper instead of creating a new `AltDriver` object. 

The goal is to make it easier to update the C# tests, for example to update the timeout or the game name for all tests in one place instead of needing to update all test cases.

**Comment by iulianatodoran** [comment]
Ran the automated tests on Samplescene game in `C#` Unity on Windows, Android, and iOS and found no problems.

**Closing the ticket.**
