### ISSUE TITLE
[Examples] Change in tests "Altom" name in imports for C# package and update the builds and the readmes of all examples

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1038]
## Description
 
- Apply in tests in example projects the changes brought in the `feature-proxy` branch by https://github.com/alttester/AltTester-Unity-SDK/issues/984 for **the next release of the tester** (for pro 1.0 release)
- The example builds and the readme.md files will be updated, considering the new release (2.0.1)
- The driver will be updated
- The dotnet version will be updated
## Additional info

For each example project a separate ticket should be opened when the task is taken by an assignee and linked to this parent ticket
- https://github.com/alttester/EXAMPLES-NewInputSystem--CoinCollector-CSharp/issues/5
- https://github.com/alttester/EXAMPLES-NewInputSystem--RollABall-CSharp/issues/7
- https://github.com/alttester/EXAMPLES-CSharp-Android-AltTrahCat/issues/2
- https://github.com/alttester/EXAMPLES-CSharp-Standalone-AltTrashCat/issues/3
- https://github.com/alttester/EXAMPLES-CSharp-iOS-AltTrahCat/issues/3
- https://github.com/alttester/EXAMPLES-NewInputSystem--LeanTouch-CSharp/issues/5
- https://github.com/alttester/EXAMPLES-Python-Standalone-AltTrashCat/issues/6

**Comment by iulianatodoran** [comment]
@sandraaltom we should consider updating at least some projects in the Examples section for the next release. I didn't assign the `release pro 1.0` label yet.

**Comment by MihaiCuc98** [comment]
Considering that all of the sub-tickets of this epic are closed, I will close the epic too.

**Comment by iulianatodoran** [comment]
There are 2 examples left that need to be checked in order to close this ticket: 
- https://github.com/alttester/EXAMPLES-Python-iOS-AltTrashCat/issues/3
- https://github.com/alttester/EXAMPLES-Java-iOS-AltTrashCat/issues/2

**Comment by iulianatodoran** [comment]
✅ Checked locally the last examples mentioned in the above comment and they work as expected.

**Will be closing this ticket.**
