### ISSUE TITLE
Regular input stops working while SDK is connected to AltProxy

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1039]
### AR
 
Before using AltProxy it was ok for the SDK to use the custom input system when connected to the tests or to the desktop.
Now it becomes a problem as SDK needs to be connected to the proxy all the time which **❗stops regular input from working**.

### Additional info
 
- The finding of this bug occurred when trying and not succeding to use the keyboard input in an instrumented TrashCat game (WebGL build with AltTester Unity SDK from `feature-proxy` branch)
- This behavior has a significant impact on the AltTester Desktop users not being able to use all types of inputs in the instrumented builds while using the Desktop app (even though in running tests the input should be handled)

### ER
 
Regular input should work when SDK is connected to AltProxy.

## Testability

Check in an TrashCat instrumented build while connected to the proxy that the input from the keyboard works.

**Comment by iulianatodoran** [comment]
@sandraaltom I put this in Backlog, but it should be established with the dev team how to prioritize it considering the impact it has on the functionality of instrumented builds in relation to using the Desktop app.

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11, MacOS Big Sur v 11.7.2
- builds created in Unity version 2021.3.16f1 LTS
- _AltTester Desktop_ project from `development` branch (21.02.2023)
- _Samplescenes_  and _TrashCat_ games instrumented with AltTester Unity SDK from `development` branch

### Issues found during testing
- Context: Instrumented game connected with the Desktop app (and AltProxy started from Desktop)
- Issue: ❗ After clicking on the `Restart` button from the `AltDialog` (from `AltTesterPrefab`), after the Desktop reconnects >> **AR**: the AltDialog message is `Connected to AltProxy on [...]. Waiting for driver to connect` instead of >> **ER**: `Connected to AltProxy on [...]. Driver connected.`

### Conclusions
For the above-mentioned issue **will reopen the ticket**

**Comment by robert-altom** [comment]
This issue should be fixed in PR: #1140.

**Comment by iulianatodoran** [comment]
Retested and the issue mentioned in the above comment reproduces if the `Restart` action is performed at least twice after the first connection with the Server.

@robert-altom I am reopening the ticket.

**Comment by robert-altom** [comment]
I fixed this in #1165.

**Comment by iulianatodoran** [comment]
Waiting for https://github.com/alttester/AltTester-Desktop/pull/943 to be merged for testing this ticket

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11, MacOS Big Sur v 11.7.6
- builds created in Unity version 2021.3.16f1 LTS
- _AltTester Desktop_ project from `development` branch (05.05.2023)
-  _TrashCat_ game instrumented with AltTester Unity SDK from `development` branch

### Tests performed and results
- ✅ Checked that while the game is connected with the AltServer the regular input can be performed on the game side
- ✅ Checked that while the game and Desktop are connected with the AltServer the regular input can be performed in the Desktop app, but not in the game
- ✅ Checked that before the game is connected to the AltSever the dialog message is: `Waiting to connect to AltServer on 127.0.0.1:13000 with app name:'__default__'.`.
- ✅ Checked that after the game is connected to the AltServer the dialog message is: `Connected to AltServer on 127.0.0.1:13000 with app name:'__default__'. Waiting for driver to connect.` and until a Driver is connected the input works. 
- ✅ Checked that after both the game and a Driver are connected to the AltServer the dialog message is minimized with the message: `Connected to AltServer on 127.0.0.1:13000 with app name:'__default__'. Driver connected.` and the input is disabled. 
- ✅ Checked that when all the Drivers disconnect the `AltDialog` is maximized with the message: `Connected to AltServer on 127.0.0.1:13000 with app name:'__default__'. Waiting for driver.` and the input will be enabled again. 
- ❌  Checked that after clicking on the `Restart` button in `AltDialog` (from `AltTesterPrefab` in the SDK build), after the Desktop reconnects the AltDialog message is `Connected to AltServer on [...]. Driver connected.` > there is already a logged ticket for this issue on the Desktop side https://github.com/alttester/AltTester-Desktop/issues/991
- ❌  Checked that after clicking twice on the `Restart` button in `AltDialog` (from `AltTesterPrefab` in the SDK build), after the Desktop reconnects the AltDialog message is `Connected to AltServer on [...]. Driver connected.` but it is the same problem as above 

### Notes
- different scenarios for using custom/regular input were tested in https://github.com/alttester/AltTester-Unity-SDK/issues/1041

### Issues found during testing
- https://github.com/alttester/AltTester-Desktop/issues/991

### Conclusions
As the main goal of this ticket was about Regular Input, the problems found will be addressed in the above-mentioned ticket (or/and in new ones if it is necessary on the SDK or AltProxy side) (@robert-altom )

The purpose of this ticket was achieved. Closing the ticket.
