### ISSUE TITLE
Compiling error when project only has 1 active input system

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1042]
To fix this issue just switch the line 266 with 269 in InputController.cs

## Steps to reproduce
1. Open a project that has 1 active input system(new or old input system but not both)

### AR
 
Throws error in Unity Console Window
### ER
 
Compiles the project without issues

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11
- Unity v 2020.3.43f1, 2021.3.16f1, 2022.2.1f1
- AltTester Unity SDK from `development` branch (12.01.223)

### Tests performed and results
- ✔️ Checked in Unity that when opening/playing in _AltTester Editor_ a project that has the setting  `Input Manager (Old)` for _Active Input Handling_ there are no compile Input errors in the console and the _AltTester Editor_ window is accessible in the top menu
- ✔️ Checked in Unity that when opening/playing in _AltTester Editor_ a project that has the setting  `Input System Package (New)` for _Active Input Handling_ there are no compile Input errors in the console and the _AltTester Editor_ window is accessible in the top menu
- ✔️ Checked in Unity that when opening/playing in _AltTester Editor_ a project that has the setting  `Both` for _Active Input Handling_ there are no compile Input errors in the console and the _AltTester Editor_ window is accessible in the top menu

### Conclusions
The purpose of this ticket was achieved: the project is compiled without issues in the given conditions.

Closing the ticket.
