### ISSUE TITLE
Have a project that is set to use the old input system and make it possible in pipeline

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1043]
To make sure we don't have compiling issues if there only one active input, we would need to have a project that can be built automatically from pipeline to check that there are no issues.

**Comment by gomboskriszta15** [comment]
The project can be found here https://github.com/alttester/trashcat.

**Comment by iulianatodoran** [comment]
✅  Checked for the [Trashcat game in the repository ](https://github.com/alttester/trashcat/tree/1-update-alttesterunitysdk-to-180) in `ProjectSettings.asset` file on `1-update-alttesterunitysdk-to-180`   branch that it uses the Old Input System when it runs on pipelines.

_Note_: There ar still problems for building iOS and MacOS builds on pipeline, so right now the builds cannot be built on the `master` branch. @sandraaltom
