### ISSUE TITLE
Have a project that is set to use the new input system and make it possible in pipeline

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1044]
To make sure we don't have compiling issues if there only one active input, we would need to have a project that can be built automatically from pipeline to check that there are no issues.

**Comment by gomboskriszta15** [comment]
Solved in https://github.com/alttester/EXAMPLES-NewInputSystem--RollABall-CSharp/pull/6.

**Comment by RobertPoienar** [comment]
Closing this issue because there nothing to review. The review will happen in the PR @gomboskriszta15  linked
