### ISSUE TITLE
[Documentation] Make available for users separate documentations for PRO and older versions

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1058]
## Description
 
We should make available for users the possibility to access the documentation on our website for the Pro version and also for older versions (to be decided for what and how many versions)

**Comment by iulianatodoran** [comment]
@sandraaltom I put this ticket on `Backlog`

**Comment by sandraaltom** [comment]
This ticket can be done after the release.

**Comment by sandraaltom** [comment]
This is already implemented with https://github.com/alttester/AltTester-Unity-SDK/issues/1202 and https://github.com/alttester/AltTester-Desktop/issues/1126. 
Closing this ticket.
