### ISSUE TITLE
Fix examples for C# and Java in the documentation under section WaitForObject

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1063]
## Steps to reproduce
Go to https://altom.com/alttester/docs/sdk/pages/commands.html#waitforobject

## Actual result
In C# the example is with WaitForObjectNotBePresent and the Java example could be more straight forward. 

### Additional info
From Discord https://discord.com/channels/744769398023127102/748145672557035625/1065552367388463154

## Expected result
Give examples with the correct command.

**Comment by iulianatodoran** [comment]
Checked in the Staging documentation that the changes implemented in this ticket are included correctly and completeley and that there are no Layout/Text issues.

Closing the ticket.
