### ISSUE TITLE
Investigate if tests can be run on a public machine

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1065]
## Description
 
Investigate if the tests can run on a public machine (e.g. GitHub runner, GitLab, ...)

**Comment by iulianatodoran** [comment]
### Tests performed and results
Checked in the Staging docs that in the `Running tests using the device cloud services` page there is a new section added for `GitHub`:
- ✅ with correct and relevant information without typos or layout issues
- ✅ useful and functional links
- ✅ and an example project with a functional link to the correct repository

### Conclusion
The purpose of this ticket was achieved.

**Closing the ticket.**
