### ISSUE TITLE
Investigate if Desktop can start the Proxy without GUI

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1067]
## Description
 
To investigate if the Desktop can start proxy without GUI (Note: Unity has documentation about how to start an app without GUI): 

- if it works: we should add in the documentation how to do that
- if it doesn't work: we should fix it and then add in the documentation how to do that

**Comment by rucindrea** [comment]
It looks like we can start it with "-batchmode" parameter and it works:

`/Users/rucindrea/workspace/AltTester-Desktop/AltTesterDesktop/Builds/AltTesterDesktop.app/Contents/MacOS/AltTester\ Desktop -batchmode`

We need to decide if we want to have a way to change the default port for release 1.0 and we also need to document how to start it in batch mode.

**Comment by RobertPoienar** [comment]
https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Editor/AltTestRunner.cs#L478 here can be found an example how to read arguments from command line, I think it's helpful to implement the option to change the port

**Comment by sandraaltom** [comment]
@rucindrea I created 3 new tickets that follow-up this investigation: 

- one for documenting start of proxy in batch mode > https://github.com/alttester/AltTester-Unity-SDK/issues/1146 
- one for implementing a way of changing the default port > https://github.com/alttester/AltTester-Unity-SDK/issues/1148 
- update an existing ticket for limiting in the Freemium version the functionality of starting the proxy without GUI > https://github.com/alttester/AltTester-Desktop/issues/821
- one for researching the impact of this limitation > https://github.com/alttester/AltTester-Unity-SDK/issues/1147 

Closing this ticket.

**Comment by RobertPoienar** [comment]
Closing this issue because it was moved to Done
