### ISSUE TITLE
Add documentation for custom vs regular input toggling

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1073]

**Comment by iulianatodoran** [comment]
Will reopen this ticket in order for @gomboskriszta15 to reformulate in the documentation what was introduced in https://github.com/alttester/AltTester-Unity-SDK/issues/1041 that is related to this ticket

**Comment by iulianatodoran** [comment]
### Tests performed and results
✅ Checked in the Staging documentation that in the _Get Started_ section > _Run your game in Unity or on desired platform_ subsection, the complete and correct information is included, with no UI/layout issues
![image](https://user-images.githubusercontent.com/62327834/215456562-d2f64b96-bfbb-40b4-939e-74155c88b3be.png)
✅ Checked in the Staging documentation that in the _Advanced Usage_ section > _Custom input vs. regular input_ subsection, the complete and correct information is included, with no UI/layout issues
![image](https://user-images.githubusercontent.com/62327834/215455869-8dc1f91b-1c2b-49d1-842b-bdbc5188410d.png)

### Conclusion
- the purpose of this ticket was achieved

**Closing the ticket**.
