### ISSUE TITLE
Half of the icon gets outside of the screen

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1080]
## Steps to reproduce
Move the icon inside of the instrumented app near to the screen edges.
## Actual result

The icon is half way outside of the screen.

## Expected result

The icon should stay entirely inside the screen.

**Comment by iulianatodoran** [comment]
### Testing Environment
- SampleGame build **played in Editor**, **Standalone** and  **Android**  - instrumented with AltTester Unity SDK from the `development` branch in 30.01.23
- Unity v 2021.3.16f1 (Windows/Mac)

### Tests performed and results
- ✅ Checked while the game is started that the popup for the `AltTesterPrefab` can be moved (in the game with `Custom Input` setting unchecked and in AltTester Desktop with `Custom Input` checked) inside the screen of the game without partially exiting the screen
    - _Notes:_ Found 2 popup issues (that might be related) but are addressed another ticket #1089 as it might not be included in the 1.8.2 Hotfix 
- ✅ Checked that on click the popup for the `AltTesterPrefab` opens/closes the AltDialog window as expected

### Conclusions
-  The purpose of this ticket was achieved
- **Closing the ticket**
