### ISSUE TITLE
[Update docs] We no longer support Unity 2018

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1091]
https://discord.com/channels/744769398023127102/748145672557035625/1069824306223267901 In this message from Discord someone tried to import AltTester SDK into Unity 2018 and had errors. I reproduced this problem and seems like we cannot find a way to support Unity 2018 because of the NIS.
TO DO: update FAQ to state that we no longer support 2018.

**Comment by iulianatodoran** [comment]
✅ Checked in the Live documentation in the FAQ section, that the Unity version compatible with AltTEster Unity SDK is  `2020.3.0` or higher
✅ Checked that there are no Layout/Text issues in the FAQ section

Closing the ticket.
