### ISSUE TITLE
[Android] Configure the Websocket Clients to be Proxy Aware

### ISSUE THREAD

**Issue by robert-altom** [alttester/AltTester-Unity-SDK#1100]
> If the HTTP client library used in the apps is able to detect and configure the system proxy, then those apps are called Proxy Aware.

**Comment by alexrotaru** [comment]
let's try to use native code for android (maybe also iOS) to detect the system proxy.

**Comment by rucindrea** [comment]
This is now working and tested since the python tests are being run in Browserstack even in the pipeline.
