### ISSUE TITLE
WebGL build freezes [Unity 2022]

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1104]
## Steps to reproduce
Create WebGL build using Unity 2022.2.1f1/2022.2.5f1. 

Issue was created after testing this ticket: https://github.com/alttester/AltTester-Unity-SDK/issues/982 (find the issue at Main conclusions, point 2).

## Expected result

Build should work without freezing.

**Comment by iulianatodoran** [comment]
Re-tested on 22.02.23 with a TrashCat WebGL build created in Unity v `2022.2.7f1` on Windows 11 and Mac OS  Big Sur v 11.7.2 and there are no more issues of any kind. 

Closing the ticket.
