### ISSUE TITLE
WebGL build cannot be loaded from saved location [Unity 2021]

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1105]
## Steps to reproduce
Create a WebGL build with Unity 2021.3.16f1 using the NIS.

## Actual result

Build cannot load if opened later from the saved location in some browsers: Windows Chrome (Incognito), Windows Edge (InPrivate) and MacOS Safari (Private).

### Additional info
Check out this issue for reference: https://github.com/alttester/AltTester-Unity-SDK/issues/982 

## Expected result

Build should load correctly from saved location.

**Comment by iulianatodoran** [comment]
@gomboskriszta15 the issue occurs on all specified browsers if opening the build with the `http-server` command from the build location. However, if using the `Live Server` extension from VSCode to open the build the issue occurs only in the MacOS Safari browser, and not anymore on Windows Chrome and Windows Edge

**Comment by iulianatodoran** [comment]
Tried again to open the 2020, 2021 an 2022 builds using `Live Server` extension from VSCode on MacOS Safari browser Version `16.2 (16614.3.7.1.7, 16614)` and the issue does not occur anymore (possibly after a recent browser update). 

Closing the ticket.
