### ISSUE TITLE
[Documentation] Document reverse port forwarding

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1114]
## Additional info

Part of the epic https://github.com/alttester/AltTester-Unity-SDK/issues/1071

**Comment by iulianatodoran** [comment]
@sandraaltom I added the release `pro 1.0 label `

**Comment by sandraaltom** [comment]
@gomboskriszta15 In this ticket we should document the:

- reverse port forwarding on Android 
- workaround for the iOS (since we agreed to postpone

**Comment by iulianatodoran** [comment]
### Environment
Staging documentation

### Tests performed and results
- ✅ Checked in the _API_ section that there is a section for `AltReversePortForwarding` for Android with all the necessary information (description, methods, parameters, examples for C#, Java, Python)
- ✅ Checked in the _API_ section that there is a section for the iOS case with a valid workaround (since IProxy does not have a way of setting up reverse port forwarding)
- ✅ Checked in the _Advanced usage_ section that there are the following sections with their subsections, with correct/complete/relevant information, graphics, and links
  - _What is reverse port forwarding and when to use it_
  - _Connect the AltTester Unity SDK running inside the app to the AltServer_
- ✅ Checked that there are no typos/layout issues/broken links in the changed areas

### Notes
- for some typos, display issues or small incorrect information present in some changed areas informed the developer to fix them in a different PR for documentation

### Conclusion
The purpose of this ticket was achieved. For some issues informed the developer and will fix them separately.

**Closing the ticket.**
