### ISSUE TITLE
Change AltProxy name to Server

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1115]
## Description
 
Change the `AltProxy`/ `Proxy` name to `Server` in all places where it is mentioned (scripts, prefabs, tests, documentation)

**Comment by robert-altom** [comment]
Fixed in #1122

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11, MacOS Big Sur v 11.7.4
- Unity version 2021.3.16f1 LTS
- _AltTester Desktop_ project from `816-update-driver-and-proxy` branch (01.03.2023)
- AltTester Unity SDK project on `development` branch
- _Samplescenes_  and _TrashCat_ games instrumented with AltTester Unity SDK from `development` branch

### Tests performed and results
- ✅ Checked in the `AltDialog` from `AltTesterPrefab` that the `AltProxy` name is replaced by `AltServer` name in the messages
- ✅ Checked in the project repo that `AltProxy`/`Proxy` name is replaced by `AltServer` name in the expected places in all the files that needed to be changed
- ✅ Checked in docs that AltProxy`/`Proxy` name is replaced by `AltServer` name
- ✅ Checked that an instrumented build is able to connect to AltServer and Desktop app successfully

### Conclusion
The purpose of this ticket was achieved.

**Closing the ticket.**
