### ISSUE TITLE
Rename Game and GameName to App and AppName

### ISSUE THREAD

**Issue by robert-altom** [alttester/AltTester-Unity-SDK#1121]
Related to alttester/AltProxy#18

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11, MacOS Big Sur v 11.7.4
- builds created in Unity version 2021.3.16f1 LTS
- _AltTester Desktop_ project from `816-update-driver-and-proxy` branch (01.03.2023)
- AltTester Unity SDK project on `development` branch
- _Samplescenes_  and _TrashCat_ games instrumented with AltTester Unity SDK from `development` branch

### Tests performed and results
- ✅ Checked in the `AltDialog` from `AltTesterPrefab` that the `game name` is replaced by `app name` in the messages
- ✅ Checked in the project repo that `Game` and `GameName` are replaced by `App`/ `Application` and `AppName` in the expected places in all the files that needed to be changed
- ✅ Checked that an instrumented build is able to connect to Proxy server and Desktop app successfully

### Notes
- The changes in the documentation files are addressed in another issue #1143  

### Conclusion
The purpose of this ticket was achieved.

**Closing the ticket.**
