### ISSUE TITLE
Add new command WaitForComponentProperty

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1133]
**Describe the feature/enhancement**

this is a wrapper to GetComponentProperty similar with how WaitForObject is a wrapper to FindObject.
This methods should wait until the property is set to the desired value

This will require implementation for all 3 languages

(Please describe your feature/enhancement idea)

**What is the reason you need this feature?**

(Offer us some context about how you will use this feature or why you this enhancement)

(Select which label is suitable for your issue)
/label ~feature  /label ~enhancement

**Comment by MihaiCuc98** [comment]
Test session is **done**. What was checked:
- All the test ideas and the checks can be viewed in this spreadsheet: https://docs.google.com/spreadsheets/d/1li334EZ3yLd6htYEPjiC_LU3Lrh6YoXeiYKeH8vFjxk/edit?usp=sharing

❗ I logged all the findings in one ticket: [[WaitForComponentProperty] Multiple issues with the WaitForComponentProperty method](https://github.com/alttester/AltTester-Unity-SDK/issues/1185).

Considering that, I will move this ticket into **Done**. CC: @SandyEma9
