### ISSUE TITLE
[Documentation] Explain how user should add AltTester asmdef to their asmdef

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1134]
Explain in which asmdef user should add our AltTester asmdef and fix the wrong information https://altom.com/alttester/docs/sdk/pages/faq-troubleshooting.html
`How can I use the Input from AltTester Unity SDK if my project is using Assembly Definitions ?`

### Additional info
 
Part of epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1071

**Comment by iulianatodoran** [comment]
### Tests performed and results
✅ Checked on the Staging documentation that in the _FAQ_  > _Troubleshooting_ section, there is a subsection dedicated to `How can I use the Input from AltTester Unity SDK if my project is using Assembly Definitions ?`
✅ Checked that for above-mentioned subsection contains the explanation for referencing `AltTesterUnitySDK.asmdef` in the personal .asmdef files that contain any kind of input
✅ Checked that there are no typos/layout issues in the changed area

  ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/6be6c35b-27e7-40f7-a156-28767a116c04)

### Conclusions
The purpose of this ticket was achieved.

**Closing the ticket.**
