### ISSUE TITLE
[Documentation] Add in the SDK documentation how to make a separate solution for running the C# tests outside the Unity Editor

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1137]
## Description
 
Document in the SDK documentation how to make a separate solution for running the C# tests outside the Unity Editor.

**Comment by gomboskriszta15** [comment]
Closing this ticket as we already have a section for this in the docs https://altom.com/alttester/docs/sdk/pages/get-started.html#write-and-execute-first-test-for-your-game under the `C#` tab.
