### ISSUE TITLE
[Examples] Update examples that use port forwarding to use reverse port forwarding

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1139]
## Description
 
For the new architecture with Proxy we should update all the examples that use port forwarding to use reverse port forwarding:
- https://github.com/alttester/EXAMPLES-CSharp-Android-AltTrahCat >> Issue: https://github.com/alttester/EXAMPLES-CSharp-Android-AltTrahCat/issues/6
- https://github.com/alttester/EXAMPLES-CSharp-iOS-AltTrahCat >> Issue: https://github.com/alttester/EXAMPLES-CSharp-iOS-AltTrahCat/issues/7
- https://github.com/alttester/EXAMPLES-Python-Android-with-Appium-AltTrashCat >> Isue: https://github.com/alttester/EXAMPLES-Python-Android-with-Appium-AltTrashCat/issues/4
- https://github.com/alttester/EXAMPLES-Python-Android-AltTrashCat >> Issue: https://github.com/alttester/EXAMPLES-Python-Android-AltTrashCat/issues/1
- https://github.com/alttester/EXAMPLES-Python-iOS-AltTrashCat >> Issue: https://github.com/alttester/EXAMPLES-Python-iOS-AltTrashCat/issues/3
- https://github.com/alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat >> Issue: https://github.com/alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat/issues/3
- https://github.com/alttester/EXAMPLES-Java-iOS-AltTrashCat >> Issue: https://github.com/alttester/EXAMPLES-Java-iOS-AltTrashCat/issues/2

## Additional info

For each project should be created separate tags for the `1.8.2` version (the last with the old architecture) and the releleased version of the new architecture.

**Comment by iulianatodoran** [comment]
@sandraaltom We should decide what example projects will be included in the Pro 1.0 release in order to update them

**Comment by MihaiCuc98** [comment]
Considering that all of the sub-tickets of this epic are closed, I will close the epic too.

**Comment by iulianatodoran** [comment]
There are 2 examples left that need to be checked in order to close this ticket: 
- https://github.com/alttester/EXAMPLES-Python-iOS-AltTrashCat/issues/3
- https://github.com/alttester/EXAMPLES-Java-iOS-AltTrashCat/issues/2

**Comment by iulianatodoran** [comment]
✅ Checked locally the last examples mentioned in the above comment and they work as expected.

**Will be closing this ticket.**
