### ISSUE TITLE
[WebGL] Cannot paste into input fields in the AltDialog window

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1145]
## Steps to reproduce
 
1. Open in any browser a WebGL build instrumented  with AltTester SDK (from `development` branch)
2. Try to paste something into the input fields for host, port and app name

### AR
 
In step 2 cannot paste into the input fields

### ER
 
In step 2 should be able to paste into the input fields (just like for builds on other platforms)

**Comment by iulianatodoran** [comment]
@sandraaltom I put this ticket in `Backlog`

**Comment by sandraaltom** [comment]
Triaged Week no. 43, 2023. Not going to fix this, as it is a Unity bug.
