### ISSUE TITLE
[Proxy] Implement a way to change the default port

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1148]
Based on the investigation done in https://github.com/alttester/AltTester-Unity-SDK/issues/1067, the Proxy can be started without GUI by using the "-batchmode" parameter.
We decided to limit this functionality in the Freemium version and to make it available only for the Pro one. 
Still, we need to give the users the option to change the default port. 

## Description
 
We should have a way to change the default port.

**Comment by RobertPoienar** [comment]
Added a way to change the port when I was doing the ticket for limiting free user to use no GUI Desktop
