### ISSUE TITLE
[Android - Connection Dialog] Slow connection to the server when the IP was changed and then the restart button was pressed

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1149]
The connection to the server is slow when the IP is changed and the restart button is pressed.
## Steps to reproduce
1. Create an Android build with the default IP address and put the build on a mobile device. (_The purpose of this step is to reach a situation where it is necessary to change the IP_)
2. Open the new apk and put the IP of the PC (server) then press the _Restart_ button.

## Actual result
The connection is slow (around 2-3 minutes) and all this time, the app is stuck.

## Expected result
The connection should be made much faster.

## Testability
From the status discussion: the main areas that should be checked are the client side and the server side.

**Comment by sandraaltom** [comment]
@MihaiCuc98 / @iulianatodoran Could you please re-test this?

**Comment by MihaiCuc98** [comment]
This behavior is fixed in version 2.0.1. Considering this information, I will close this issue.
