### ISSUE TITLE
[Documentation] Insert steps for creating setup for Java tests project

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1152]
## Description
 
At the moment we don't have anywhere documented a setup for a tests project in Java. Would be nice to have this included in our documentation for people who use the SDK to get them started.

**Comment by iulianatodoran** [comment]
@sandraaltom I put this in `Backlog`

**Comment by MihaiCuc98** [comment]
The steps for creating a Java testing setup are in: https://docs.google.com/document/d/12bzWJDvBh_Ca0pQRE66KuBJoLjhPLp48JmjpwYpuipU/edit

**Comment by iulianatodoran** [comment]
### Test location
 [Staging docs (development)](https://staging-alttesterdotcom-staging.kinsta.cloud/docs/sdk/pages/get-started.html#write-and-execute-first-test-for-your-app
):
- Section: _Get Started_ 
- Subsection: _Write and execute first test for your app_

### Test performed and results
- ✅ Checked that the `Java` tab is displayed in the subsection
- ✅ Checked that `Java` tab contains correct, relevant, and detailed information on the necessary steps to create setups and run Java tests in terminal
![image](https://user-images.githubusercontent.com/62327834/230372415-8ad427bd-1760-4f27-8fa1-2b3ab4e805d7.png)
- ✅ Checked that all links in the tab are functional and direct to the expected location
- ✅ Checked that there are test examples for the `Java` tab (_Note_: Android and iOS examples will be updated in https://github.com/alttester/AltTester-Unity-SDK/issues/1114)
- ✅ Checked that there are no typos, display, or layout issues on the page

### Notes
- there is a reference of the `pro 1.0` release that is most probably not the final version name that should be rechecked after the decision on the version name is taken (link ticket here)

### Conclusion
- the purpose of this ticket was achieved

**Closing the ticket.**
