### ISSUE TITLE
[Legal] Compliance with the Apple App Store / Google Play Store 

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1161]
In order to make our sdk a package, we need to make sure that we comply with the "Package" requirements from the Unity Editor Software Terms & UPM Guidelines. 

## Description
 
- If applicable, we need to make sure that our SDK package complies with Apple App Store / Google Play Store. 

> The [UPM Guidelines](https://docs.google.com/document/d/10fI5jUHlYfWRY-6uctwz1bOZyLoZyXY6AN5Gs_B2K90/edit) state that `You should not use a Package that violates the Apple App Store or Google Play Store guidelines.`

**Comment by RobertPoienar** [comment]
I read Apple and Google store Guidelines and we are compliant with it so I'm closing this issue.
