### ISSUE TITLE
[Documentation - USEFUL LINKS] Wrong link for Maven Repository

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1188]
## Steps to reproduce
1. Open https://alttester.com/docs/sdk/
2. Navigate to the _USEFUL LINKS_ setion.
3. Click on `Maven Repository`.

### AR
The link redirects to a 404 page.

### ER
The link of the Maven Repository should be: https://mvnrepository.com/artifact/com.alttester/alttester

**Comment by ReichEdvin** [comment]
Also fix for #1189

**Comment by MihaiCuc98** [comment]
Verified as fixed in STAGING.
