### ISSUE TITLE
[Research/Testing] Investigate and test the reverse port forwarding solution for iOS

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1197]
While working on https://github.com/alttester/AltTester-Unity-SDK/issues/1114, we realised we need to find a solution for the reverse port forwarding on iOS.  

@alexrotaru proposed the following as a potential solution: to set the iPhone as a personal hotspot and then to add in the game the IP of the local machine. In the routing table, the personal hotspot network would be secondary, therefore the traffic shouldn't be redirected through the hotspot. 
![image](https://user-images.githubusercontent.com/112623086/230353549-b1edd5bd-db88-462e-9e5e-2c1ddeb52b95.png)

## Description
 
We should use this task to investigate and test the proposed solution.
- first, the pipeline should be set for iOS (@RobertPoienar )
- we should also investigate if the port could be programatically set in the game (@RobertPoienar )
- the Desktop should be on a Mac from where the created build is then added in the pipeline  (@iulianatodoran, @MihaiCuc98, support from @RobertPoienar if needed)
- the tests should be done in the pipeline: with an iOS build and an iPhone that's configured to be in proxy mode (@iulianatodoran, @MihaiCuc98, support from @RobertPoienar if needed)

**Comment by pavel-tds** [comment]
Hey you guys, just wondering why did you disable iproxy option in the first place?

**Comment by MihaiCuc98** [comment]
Considering that we have a valid workaround for the reverse port forwarding on iOS and it is described at https://alttester.com/docs/sdk/latest/pages/advanced-usage.html#in-case-of-ios, I will close this ticket.
