### ISSUE TITLE
[Documentation - AltDriver] Typos in parameter's description from 'SetStaticProperty'

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1201]
### Steps to reproduce

1. Check description for `propertyName` and `componentName` parameters from [SetStaticProperty](https://alttester.com/docs/sdk/pages/commands.html#setstaticproperty)

### Actual Result
![image](https://user-images.githubusercontent.com/62647565/230598655-69a79c10-53e7-420b-8a68-011ced05a671.png)

### Expected
Improve description of parameters from [SetStaticProperty](https://alttester.com/docs/sdk/pages/commands.html#setstaticproperty)

**Comment by SandyEma9** [comment]
@robert-altom @RobertPoienar @gomboskriszta15 @ReichEdvin @ralupopa @iulianatodoran

**Comment by ralupopa** [comment]
Very fast, but `seted` is not correct. Either use `set` as this is [past tense](https://pasttenses.com/set-past-tense) or reformulate (eg [SetComponentProperty](https://alttester.com/docs/sdk/pages/commands.html?highlight=findobjectatcoordinates#settimescale))

I used a generic expected cause I considered those descriptions can be reviewed from other perspectives

**Comment by MihaiCuc98** [comment]
Verified as fixed in `LIVE`. I will move this ticket into `Done`.
