### ISSUE TITLE
[Documentation] Have Release notes or versioned documentation for AltTester Unity SDK

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1202]
**Describe the feature/enhancement**

Each new version of AltTester Unity SDK contains additions, improvements, fixes. Observed that there are blog posts detailing these. Would be useful and easier if documentation for AltTester Unity SDK has a `Release notes` section (similar with how AltTester Desktop has).

A bigger enhancement would be to be able to view documentation by selecting versions.
![image](https://user-images.githubusercontent.com/62647565/230602201-e498a7da-73ac-4ef1-9079-ae490184b30a.png)

**What is the reason you need this feature?**
To be easier to search in which version a specific command was added or fixed.

**Comment by MihaiCuc98** [comment]
Tested in [#1126](https://github.com/alttester/AltTester-Desktop/issues/1126)
