### ISSUE TITLE
Parameter 'parameters' is required for `CallStaticMethod` even if it's optional in specs

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1205]
**In what language is the test written?** 
C#

**What version of AltTester Unity SDK are you using?**
1.8.0

**The OS from where you are running the test?**
Windows 10

### Summary
Error displayed about `parameters` being required when using method `CallStaticMethod`

### Steps to reproduce

1. Call AltDriver method `CallStaticMethod` without parameters, just provide: 
- typeName
- methodName
- assemblyName

![image](https://user-images.githubusercontent.com/62647565/231149326-6ace339f-262c-43b3-ae36-18e194428f0c.png)

2. Execute test which calls function 

**Actual result**
Displayed error:
`error CS7036: There is no argument given that corresponds to the required parameter 'parameters' of 'AltDriver.CallStaticMethod<T>(string, string, string, object[], string[])'`

**Expected behavior**
According to [CallStaticMethod specs](https://alttester.com/docs/sdk/pages/commands.html#callstaticmethod) `parameters` parameter is optional, so should be able to use method without providing `parameters`.

Additionally please review what was intention for this method, in case it was wanted to have `parameters` optional, than update documentation.

**Notes:**
- searched through [release notes](https://github.com/alttester/AltTester-Unity-SDK/releases) and did not find anything related to this method in latest versions 1.8.1, 1.8.2 so suppose the behavior is relevant for these versions as well.
- found old tickets related to this function https://github.com/alttester/AltTester-Unity-SDK/issues/592 and https://github.com/alttester/AltTester-Unity-SDK/issues/925 
- I searched tests for this method and found [TestCallStaticMethod in TestForScene1TestSample](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Examples/Test/Editor/Driver/Testforscene1TestSample.cs#L837) if `parameters` is to be optional, please add tests without providing it when calling method.

### Relevant logs and/or screenshots

Just for reference this is hierarchy in AltTester Desktop
![image](https://user-images.githubusercontent.com/62647565/231150242-2e6f3565-ce27-4f0d-b3a4-937a5799afdd.png)

![image](https://user-images.githubusercontent.com/62647565/231151462-befb39f3-96c1-4782-881e-41f45fe48bd2.png)

**Comment by ralupopa** [comment]
fyi @sandraaltom

**Comment by MihaiCuc98** [comment]
Closing this ticket.
