### ISSUE TITLE
[WebGL] The SDK always uses the __default__ app name. 

### ISSUE THREAD

**Issue by robert-altom** [alttester/AltTester-Unity-SDK#1207]

**Comment by iulianatodoran** [comment]
Waiting for https://github.com/alttester/AltTester-Desktop/pull/943 to be merged for testing this ticket

**Comment by iulianatodoran** [comment]
✅ Tested with the latest `development ` (03.05.23) instrumented SDK build and the SDK is able to use different app names besides the` __default__` name to connect to AltServer (and AltTester Desktop)

**Closing the ticket.**
