### ISSUE TITLE
[Documentation] Inconsistent title - commands for PointerDown/Up/Enter/Exit commands

### ISSUE THREAD

**Issue by ElisaSzilagyi** [alttester/AltTester-Unity-SDK#1215]
**In what language is the test written?** 
C#

**What version of AltTester Unity SDK are you using?**
1.8.2

**The OS from where you are running the test?**
Windows 10

### Summary

Searching through the specifications of **PointerDown, PointerUp, PointerEnter, and PointerExit commands**, I noticed that they are not used in the code with the same names as their previous titles, but rather with **PointerDownFromObject, PointerUpFromObject, PointerEnterObject, and PointerExitObject**, which makes the documentation inconsistent in terms of title-command correspondence.

### Expected

For a moment, I wondered if PointerDown (respectively PointerUp) is a different command from PointerDownFromObject (respectively PointerUpFromObject). I expect the title to be the same as the command used.

### Relevant logs and/or screenshots

[Documentation](https://alttester.com/docs/sdk/pages/commands.html#pointerdown).

![image](https://user-images.githubusercontent.com/110525069/233570989-b44f9767-a3b0-4122-ac3f-f3091df34a98.png)
![image](https://user-images.githubusercontent.com/110525069/233571061-5593a5e8-8ca5-49ca-b4da-90edf8225855.png)
![image](https://user-images.githubusercontent.com/110525069/233571142-5ae95846-9376-43f4-b714-85585045f818.png)
![image](https://user-images.githubusercontent.com/110525069/233571238-f04b6db2-dfe2-4d41-b9b8-122813b07efa.png)

**Comment by ralupopa** [comment]
fyi @sandraaltom

**Comment by iulianatodoran** [comment]
After scrolling through the repo project decided that solely the C# commands should be changed to be consistent with other languages, so the C# command should have the `Object` and `FromObject` removed from the names. Also, the old commands should be deprecated.

**Comment by iulianatodoran** [comment]
✅ Checked in the Staging documentation that the examples for `PointerDown/Up/Enter/Exit `commands are consistent with the API in the SDK repo

Considering the above information, **I will move this ticket to `Done`.**
