### ISSUE TITLE
[Documentation] Implemented AltObject methods are not shown in documentation (`GetWorldPosition`, `GetScreenPosition`)

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1216]
**What version of AltTester Unity SDK are you using?**
1.8.2

### Summary

Some implemented AltObject methods (eg: `GetWorldPosition`, `GetScreenPosition` ) are not shown in documentation as available to be used, but can be seen in some code examples.

### Steps to reproduce
1. Check AltObject [class implementation](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs) from SDK
2. Compare implemented list of methods with table of contents from [documentation](https://alttester.com/docs/sdk/pages/commands.html#altobject)

**Findings**

- [GetScreenPosition](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs#L79)
- [GetWorldPosition](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs#L89)
- ~[WaitForComponentProperty](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs#L105)~ this was implemented after v1.8.2, so should be added when releasing new version of sdk
- [GetAllComponents](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs#L194)
- [GetAllProperties](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs#L201)
- [GetAllFields](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs#L208)
- [GetAllMethods](https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Runtime/AltDriver/Common/AltObject.cs#L215)

fyi @sandraaltom

**Comment by MihaiCuc98** [comment]
The testing session is done. What was checked on **latest docs**:
✔ Checked the text for any typos
✔ Checked if the parameters displayed are consistent with the implementation of the methods
✔ Checked if the return objects are consistent with the implementation of the methods
✔ Checked for any layout issues
✔ Checked the tests from the example section (c# and Python)

Considering this information, I will move this ticket into `Done`.
