### ISSUE TITLE
[Documentation] Document the iOS workaround for the reverse port forwarding

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1218]
We decided to postpone [the iOS reverse forwarding solution](https://github.com/alttester/AltTester-Unity-SDK/issues/1197) for Release Pro 1.0. Because of this, we should document the workaround for Release Pro 1.0. 

## Description
 
Document the workaround solution: 

- Set the iPhone as a personal hotspot
- Then add in the game the IP of the local machine
- In the routing table, the personal hotspot network would be secondary, therefore the traffic shouldn't be redirected through the hotspot: 
![image](https://user-images.githubusercontent.com/112623086/234258208-bd5cc096-928e-4a1f-97e7-32217f2ea42c.png)

## Additional info
Part of epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1071

**Comment by iulianatodoran** [comment]
Tested in #1114 .

**Closing the ticket.**
