### ISSUE TITLE
[Reverse port forwarding] Modify the Android port forwarding methods into reverse port forwarding

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1219]
We decided that in Release Pro 1.0 we will support the reverse port forwarding for Android. 

## Description
 
Modify the Android port forwarding methods into reverse port forwarding for all the bindings: 

- C#
- Java
- Python

**Comment by MihaiCuc98** [comment]
### Testing env:

- OS: Windows 10
- builds created in Unity version 2021.3.19f1 (Windows)
- AltTester Desktop project from development branch (10.05.2023)
- TrashCat game and SampleScene instrumented with AltTester Unity SDK from development branch

### What was checked:
- C#, Python, Java: Checked if the connection is made between the bindings, app, and server when the reserve port forwarding methods is called 
- C#, Python, Java: Checked if the reversed ports are displayed when we are using the `adb reverse --list` command after the `reverse port forwarding` was called.
- C#, Python, Java: Checked if the `remove reverse port forwarding` method is working properly by checking if the previous reversed ports are not displayed anymore into the adb reversed list

### Findings:
- https://github.com/alttester/AltTester-Unity-SDK/issues/1248
- Other tests can be still run on the instrumented app even if the `remove reverse port forwarding` method was called. Agreed with the dev team that this is not a bug

Considering this information, I will move this ticket into Done.
