### ISSUE TITLE
SetText not working in Java

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1221]
## Steps to reproduce
 
1. Use set text in a test 

### AR
 
Text remains empty

## Expected result
Text to be set with the value you added as a parameter in setTExt

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows `11`, MacOS `Big Sur` v `11.7.6`
- `SampleGame` game (Android, iOS, webGL) instrumented with `AltTester Unity SDK` from `development` branch (26.04.2023)
- AltServer started in batchmode from `AltTester Desktop` project from `development` branch (25.04.2023)

### Tests performed and results
- ✅Checked that by running the automated java tests for `setText()` command on Android, iOS and WebGL the tests pass > the Text is set with the value added as a parameter in the `setText()` command 

### Notes
- the other platforms not mentioned here (Windows, MacOS) were tested separateley (on pipelines + locally by the developer)

### Conclusions
The issue is fixed and the expected behavior is met.

Closing the ticket.

**Comment by baolv68** [comment]
SetText not working in Java 
command sent: {"by":"PATH","path":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id/Text Area/Text","cameraBy":"NAME","cameraPath":"//","enabled":true,"value":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id/Text Area/Text","cameraValue":"","messageId":"1683516494632","commandName":"findObject"}
response received: {"messageId":"1683516494632","commandName":"findObject","error":null,"data":"{\"name\":\"Text\",\"id\":-1660,\"x\":738,\"y\":455,\"z\":0,\"mobileY\":264,\"type\":\"\",\"enabled\":true,\"worldX\":738.209045,\"worldY\":455.050629,\"worldZ\":0.0,\"idCamera\":-1,\"transformParentId\":-1646,\"transformId\":-1662}","isNotification":false}
command sent: {"by":"PATH","path":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id/Text Area/Text","cameraBy":"NAME","cameraPath":"//","enabled":true,"value":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id/Text Area/Text","cameraValue":"","messageId":"1683516494742","commandName":"findObject"}
response received: {"messageId":"1683516494742","commandName":"findObject","error":null,"data":"{\"name\":\"Text\",\"id\":-1660,\"x\":738,\"y\":455,\"z\":0,\"mobileY\":264,\"type\":\"\",\"enabled\":true,\"worldX\":738.209045,\"worldY\":455.050629,\"worldZ\":0.0,\"idCamera\":-1,\"transformParentId\":-1646,\"transformId\":-1662}","isNotification":false}
command sent: {"value":"lamvanbao","submit":true,"altObject":{"name":"Text","id":-1660,"x":738,"y":455,"z":0,"mobileY":264,"type":"","enabled":true,"worldX":738.20905,"worldY":455.05063,"worldZ":0.0,"idCamera":-1,"transformParentId":-1646,"transformId":-1662},"messageId":"1683516494850","commandName":"setText"}
response received: {"messageId":"1683516494850","commandName":"setText","error":null,"data":"{\"name\":\"Text\",\"id\":-1660,\"x\":738,\"y\":455,\"z\":0,\"mobileY\":264,\"type\":\"\",\"enabled\":true,\"worldX\":738.209045,\"worldY\":455.050629,\"worldZ\":0.0,\"idCamera\":-1,\"transformParentId\":-1646,\"transformId\":-1662}","isNotification":false}

**Comment by baolv68** [comment]
command sent: {"by":"PATH","path":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id","cameraBy":"NAME","cameraPath":"//","enabled":true,"value":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id","cameraValue":"","messageId":"1683516638617","commandName":"findObject"}
response received: {"messageId":"1683516638617","commandName":"findObject","error":null,"data":"{\"name\":\"Input Device Id\",\"id\":-1634,\"x\":738,\"y\":455,\"z\":0,\"mobileY\":264,\"type\":\"\",\"enabled\":true,\"worldX\":738.209045,\"worldY\":455.4535,\"worldZ\":0.0,\"idCamera\":-1,\"transformParentId\":-1632,\"transformId\":-1636}","isNotification":false}
command sent: {"by":"PATH","path":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id","cameraBy":"NAME","cameraPath":"//","enabled":true,"value":"/NewAdminManager(Clone)/PanelInfo/MiddleContentParent/objContentAccount/Device Id/Input Device Id","cameraValue":"","messageId":"1683516638724","commandName":"findObject"}
response received: {"messageId":"1683516638724","commandName":"findObject","error":null,"data":"{\"name\":\"Input Device Id\",\"id\":-1634,\"x\":738,\"y\":455,\"z\":0,\"mobileY\":264,\"type\":\"\",\"enabled\":true,\"worldX\":738.209045,\"worldY\":455.4535,\"worldZ\":0.0,\"idCamera\":-1,\"transformParentId\":-1632,\"transformId\":-1636}","isNotification":false}
command sent: {"value":"lamvanbao","submit":true,"altObject":{"name":"Input Device Id","id":-1634,"x":738,"y":455,"z":0,"mobileY":264,"type":"","enabled":true,"worldX":738.20905,"worldY":455.4535,"worldZ":0.0,"idCamera":-1,"transformParentId":-1632,"transformId":-1636},"messageId":"1683516638832","commandName":"setText"}
response received: {"messageId":"1683516638832","commandName":"setText","error":null,"data":"{\"name\":\"Input Device Id\",\"id\":-1634,\"x\":738,\"y\":455,\"z\":0,\"mobileY\":264,\"type\":\"\",\"enabled\":true,\"worldX\":738.209045,\"worldY\":455.4535,\"worldZ\":0.0,\"idCamera\":-1,\"transformParentId\":-1632,\"transformId\":-1636}","isNotification":false}
