### ISSUE TITLE
[Documentation] 404s for some links in AltTesterUnitySDK documentation

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1225]
## Steps to reproduce
 
1. Open AltTesterUnitySDK documentation
2. Open https://alttester.com/docs/sdk/pages/upgrade-guides/v-1-8-0.html and https://alttester.com/docs/sdk/pages/alttester-with-appium.html
3. Check for 404 links
### AR
 
There are links that redirect to 404. 
- https://alttester.com/docs/sdk/pages/alttester-with-appium.html -> the following link redirects to 404:
![image](https://user-images.githubusercontent.com/113912901/234808717-bed2532d-d290-4211-bf85-dc0fbb053d57.png)

- https://alttester.com/docs/sdk/pages/upgrade-guides/v-1-8-0.html -> the following link redirects to 404:
![image](https://user-images.githubusercontent.com/113912901/234808175-d2f0a1d0-bd3f-482b-b2c9-2599c2cb78a4.png)

### ER
 
There should be no links that redirect to 404.

**Comment by MihaiCuc98** [comment]
@sandraaltom I put this into ToDo.

**Comment by iulianatodoran** [comment]
✅ Checked the two links and they do not redirect to 404 anymore, they redirect where it is expected. Also other links in the pages work as expected.

**Closing the ticket.**
