### ISSUE TITLE
`WaitForCurrentSceneToBe` is implemented as void but in documentation presented as returning scene name

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1229]
**In what language is the test written?** 
C#

**What version of AltTester Unity SDK are you using?**
1.8.2

**The OS from where you are running the test?**
Windows

### Summary

Implementation for AltDriver method `WaitForCurrentSceneToBe` is different from what is explained and displayed in code example from documentation.

### Steps to reproduce

1. Check implementation for [`WaitForCurrentSceneToBe` from v 1.8.2 ](https://github.com/alttester/AltTester-Unity-SDK/blob/v.1.8.2/Assets/AltTester/AltDriver/AltDriver.cs#L437)
2. Check [documentation](https://alttester.com/docs/sdk/pages/commands.html#waitforcurrentscenetobe) 
3. Check code example for C# and Java

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/62647565/235437374-dc45774c-3ca7-4f1b-9faa-7659a31c33cc.png)
![image](https://user-images.githubusercontent.com/62647565/235437592-78c69f18-99bd-45ac-ab0c-3adbfb43e6e4.png)

![image](https://user-images.githubusercontent.com/62647565/235437503-a39fb779-6c9c-4d17-9922-41c5f7789ba2.png)

### Wanted
Either:
- if implementation desired is to have a void method => fix documentation to reflect the actual implementation behavior. Adapt all code examples.
- if returning scene name brings any value => change implementation of this method to return scene name as string.

(I did not searched for what was in the past and when / if it was changed and these mismatches appeared).

**Comment by ralupopa** [comment]
I forgot: fyi @sandraaltom

**Comment by MihaiCuc98** [comment]
The testing session is done. What was checked:
✔ Checked the text for any typos
✔ Checked if the behavior reported is no more reproducible 
✔ Checked the c# and java tests
✔ Agreed with the dev team that the Python test is working as expected

Considering this information, I will move this ticket into `Done`.
