### ISSUE TITLE
Remove unnecessary long named files

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1237]
we are getting on some project this error because the name is too long:

`error: cannot stat 'Assets/AltTester/Runtime/3rdParty/websocket-sharp/netstandard2.0/altwebsocket-sharp.GeneratedMSBuildEditorConfig.editorconfig.meta': Filename too long`

**Comment by MihaiCuc98** [comment]
Verified as fixed. Moving this into `Done`
