### ISSUE TITLE
[Input] KeyUp executes before KeyDown when they are send close to each other

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1239]

**Comment by RobertPoienar** [comment]
This is the fixed for the bug reported on the Desktop. To test this issue just make sure the problem on the desktop is no longer reproducible.

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Desktop/issues/833. 

**Closing the ticket.**
