### ISSUE TITLE
Update documentation for new version

### ISSUE THREAD

**Issue by ReichEdvin** [alttester/AltTester-Unity-SDK#1244]

**Comment by iulianatodoran** [comment]
✅ Checked in the Staging documentation that all links were updated with the new path (details in https://github.com/alttester/AltTester-Desktop/issues/1002) 

_Note_: 
- for some locations (`README.md` files from `Assets` and `Bindings` folders in repo) were the update was not yet implemented talked to @ReichEdvin  to fix it in another PR.
- will check again when the documentation is deployed on LIVE site.

Closing the ticket.
