### ISSUE TITLE
Add doc menu links to other versions of documentation

### ISSUE THREAD

**Issue by rucindrea** [alttester/AltTester-Unity-SDK#1281]
the Pro 2.0.0 doc should have links to the old version, and the old version should have links to the new ones

**Comment by rucindrea** [comment]
The previous version docs are now updated to show the info on where the latest 2.0.0 documentation is found.

**Comment by MihaiCuc98** [comment]
The testing session is done. What was checked:
✔ Checked if the old documentation (https://alttester.com/docs/sdk/index.html#) contains two links to the new documentation (SDK and Desktop)
✔ Checked if the links redirect to the new docs (pro) ->Checked both for SDK and Desktop 
✔ Checked the links are under the `Latest Version` section
✔ Checked the layout

Considering this information, I will move this ticket into `Done`
