### ISSUE TITLE
Search By Tag returns console errors when input is not defined

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1288]
Solves issue initially logged on Desktop: https://github.com/alttester/AltTester-Desktop/issues/936

**Comment by iulianatodoran** [comment]
Will be tested in https://github.com/alttester/AltTester-Desktop/issues/936

**Comment by iulianatodoran** [comment]
Closing as https://github.com/alttester/AltTester-Desktop/issues/936 was tested and closed
