### ISSUE TITLE
Click sometimes occurs near the object when using `altDriver.Click` or `altDriver.Tap` on objects with pivot placed on the edge of the object

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1294]
### _Context_:  using test scripts generated by the Recorder in AltTester Desktop

Sometimes when running tests that use the commands `altDriver.Click` or `altDriver.Tap` (generated in Recorder with `Click on objects` option for short clicks) the click is performed outside the object, near to it, as some objects have the pivot placed on their edge.

## Steps to reproduce
 
1. Connect the TrashCat iOS instrumented build with AltTester Desktop
2. In AltTester Desktop go to the `Recorder` tab and choose the `Click on objects` option
3. Start recording and using the `Click/Press` or `Tap/Swipe` action short-click on the `Store` button (on _Screenshot Area_)
5. After the `Store` panel opens click on the `X` button (top left)
6. Stop the recording and copy the steps in a test file
7. After setting up the test project run the test
8. Check where the click is made and if the click on the `X` button closes the `Store` panel

### AR
 
The click performed with `altDriver.Click(Button.GetScreenPosition())` or `altDriver.Tap(Button.GetScreenPosition())` is made outside the `X` button (near the top left corner) and does not close the `Store` panel 

### Additional info
 
Environment:
- TrashCat iOS instrumented build with AltTester Unity SDK v.2.0.0 (played on iPhone 6) using `Input Visualizer` when building
- AltTester Desktop v.2.0.0

ScreenRecording 
https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/3ae1b39c-2a87-4312-a20f-d46a8d11815c

Other notes
- if using the same script on other Android phones could not reproduce the issue (only in iPhone 6)
- when recording a Tap the commands generated by the Recorder should look like this:
```
var Button = altDriver.WaitForObject(By.PATH,"/Canvas/Background/Button", enabled: false);
altDriver.Tap(Button.GetScreenPosition());
```
- ⬆️ workaround: if  `altDriver.Tap(Button.GetScreenPosition())` is replaced by `Button.Tap()` the expected result is met: the `Store` panel is closed from the `X` button as the button is clicked on the inside

### ER
 
The click performed with `altDriver.Click` or `altDriver.Tap` should be made inside the `X` button and should close the `Store` panel

**Comment by iulianatodoran** [comment]
@sandraaltom Discussed with @RobertPoienar about this issue and I assigned the `release pro 2.01` label (in `TODO` column), but you may re-prioritise it after a discussion with the team.

**Comment by ralupopa** [comment]
If I may add a few details 😄 

Reproducing this situation as well:
- standalone build `AltTicTacToe` 2.0.0 (the one provided in package)

Not reproducing with the code generated with recorder, but when try to click with Altdriver function on Play button the action is not performed. To be more specific:

- This was generated using recorder for py and it is running successfully:
```
def test(self):
    self.altdriver.load_scene("StartScene",True)
    self.altdriver.load_scene("PlayScene",True)
    TextTMP = self.altdriver.wait_for_object(By.PATH,"/Canvas/MainContainer/Board/Slots/Slot1/Text (TMP)",enabled=False)
    self.altdriver.click(TextTMP.get_screen_position())
```
Complete running script [can be found here](https://github.com/ralupopa/AltTicTacToe-pytest/blob/main/unittest_sample/test_recorder.py)

- Trying to execute the following code snippet, the click action is not performed:
```
self.altdriver.load_scene("StartScene",True)
play = self.helper_methods.play_button
self.altdriver.click(play.get_screen_position())
```

working when using: `play.click()`
