### ISSUE TITLE
Swipe and Begin Touch use different methods to create touches

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1312]
We should use the same method to avoid code duplications and bugs. A user on discord mentioned a bug with swipe not working but Begin Touch/Move Touch and End Touch working and I think it's because how we create the touch in the swipe method. 

https://discord.com/channels/744769398023127102/1115978864431202434/1115980591117107230

**Comment by RobertPoienar** [comment]
@sandraaltom I put it for 2.0.2 because we already have some input issues added to this release and this issue should be just a simple refactoring of one method to use already existing methods

**Comment by iulianatodoran** [comment]
Tested in #1283 

**Closing the ticket.**
