### ISSUE TITLE
[Documentation] [Advanced usage] Make improvements and corrections

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1328]
## Description
 
On the following locations in the _Advanced usage_ section, there are some things that are not correct or are missing:
https://alttester.com/docs/sdk/latest/pages/advanced-usage.html#establish-connection-when-the-app-is-running-on-a-device-connected-via-usb
https://alttester.com/docs/sdk/latest/pages/advanced-usage.html#establish-connection-via-ip-when-the-app-is-running-on-a-device
- There is no need for two different ports in order to connect 2 instrumented apps to the AtlServer
- There is no mention of the `appName` and needs to be included
- It is not clear what needs to be done in AltTester Desktop (what port to be used)

## Additional info

Add also info related to BlueStack.

**Comment by gomboskriszta15** [comment]
Diagrams can be found here https://drive.google.com/drive/u/0/folders/1aCvNXZbckMl6dnf8YGQ8SyyimUEDsUA3.

**Comment by MihaiCuc98** [comment]
What was tested on `STAGING`:
✔ Checked the layout of the `Connect AltTester Unity SDK running inside the app to AltServer` section
✔ Checked if the diagrams are the expected ones for each section
✔ Checked the info from the steps of each section
✔ Checked the links of each section
✔ Checked the text of the section for any typos
✔ Checked the code snipped of each section (C#, Python, Java)

Considering this information, I will move this ticket into `done`.
