### ISSUE TITLE
[User problem] Unable to run test because getting error in connection panel

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1332]
This error message are getting some user. This user got from us a special patch of 2.0.1 but still doesn't work. 
```2023-07-04 18:44:24: InvalidCommandException: Unable to find a constructor to use for type AltTester.AltTesterUnitySDK.Driver.Commands.AltGetServerVersionParams. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'messageId', line 2, position 14.
    AltTester.AltTesterUnitySDK.Driver.Communication.DriverCommunicationHandler.handleErrors (AltTester.AltTesterUnitySDK.Driver.Commands.CommandError error) (at <6684d9bbccf241348b36c2c85a7d9486>:0)
    AltTester.AltTesterUnitySDK.Driver.Communication.DriverCommunicationHandler.Recvall[T] (AltTester.AltTesterUnitySDK.Driver.Commands.CommandParams param) (at <6684d9bbccf241348b36c2c85a7d9486>:0)
    AltTester.AltTesterUnitySDK.Driver.Commands.AltGetServerVersion.Execute () (at <6684d9bbccf241348b36c2c85a7d9486>:0)
    AltTester.AltTesterUnitySDK.Driver.AltDriver.GetServerVersion () (at <6684d9bbccf241348b36c2c85a7d9486>:0)
    AltTester.AltTesterUnitySDK.Driver.AltDriver.checkServerVersion () (at <6684d9bbccf241348b36c2c85a7d9486>:0)
    AltTester.AltTesterUnitySDK.Driver.AltDriver..ctor (System.String host, System.Int32 port, System.Boolean enableLogging, System.Int32 connectTimeout, System.String appName) (at <6684d9bbccf241348b36c2c85a7d9486>:0)
    AltDriverController.Connect (System.String host, System.Int32 port, System.String appName) (at <0b1f20582e0c4c4fb8affe4844a45d05>:0)
    ConnectionController.<connect>b__53_0 () (at <0b1f20582e0c4c4fb8affe4844a45d05>:0)
    UnityEngine.Debug:LogException(Exception)
    ConnectionController:<connect>b__53_0()
    System.Threading.ThreadHelper:ThreadStart()
```

**Comment by iulianatodoran** [comment]
### Testing environment
- _TrasCat_ iOS instrumented with AltTester Unity SDK v.2.0.1 (from `development` branch on 11.07.23) in Unity v 2021.3.16f1
- AltServer started from AltTester Desktop v.2.0.1
- device for running the build: iPhone 6 

### Tests performed and results
- ✅ Checked by trying to connect to AltServer the iOS build instrumented using the `IL2CPP` _Scripting Backend_ and `High` _Managed Stripping Level_ settings in Unity the connection is successfully established with no errors in the _Connection Panel_ in the AltTester Desktop
- ✅ Checked that the above-mentioned build can establish successful connection also in the AltTester Desktop app and there are no disconnection problems and the expected behaviors occur using the main features

### Note
- the user already tried to connect an Android `IL2CPP` build with our fix and the issue did not reproduce anymore

### Conclusion
Could not reproduce the problem anymore using an  `IL2CPP` build with the `High` _Managed Stripping Level_ so will consider the issue as fixed.

**Closing the ticket.**
