### ISSUE TITLE
[Documentation] [Advanced usage] Update info in workaround for reverse port forwarding 

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1335]
There is missing information in https://alttester.com/docs/sdk/latest/pages/advanced-usage.html#in-case-of-ios that should be added for the users who can only connect via USB cable 

## Description
 
Tasks:
- We should include this information in the _Advanced Usage > What is reverse port forwarding and when to use it > How to setup reverse port forwarding > In case of iOS_ 
  - To connect the device via USB to the machine running the Desktop app you should enable Hotspot via USB on this machine. Then AltTester can connect using the IP that the machine gets over this USB connection, which seems to always be the same.
For this to work, you need to make sure that you have the "Disable unless needed" toggle disabled in the network settings for the USB connection.
  - The hotspot network and the first device to connect to it are most of the time on 172.20.10.2 so you could always set this IP for builds for iOS
- Modify the existing information so that there is no confusion

![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/8cca71eb-44f8-4bd5-b9d4-513ad9788be0)

**Comment by MihaiCuc98** [comment]
The testing session is done. What was checked:
✔ Checked if the new info added is describing the way to use the iOS reverse port forwarding workaround
✔ Checked the info for any typos

Findings: 
- https://github.com/alttester/AltTester-Desktop/issues/1196

Considering this information, I will move this ticket into `Done`.
