### ISSUE TITLE
[Instrumented - Connection panel] Implement a way to store the previous successful connection info

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1337]
## Description
 
At this moment, the desktop store the last connection info for which a successful connection was made.  Considering that, we should implement a way through which the data from the connection pop-up is also stored.

**Comment by iulianatodoran** [comment]
## Testing environment
- OS: Windows 10, MacOS Big Sur 11.7.7
- AltTester Desktop Windows, MacOS from `development` branch (02.08.2023) 
- Unity v 2021.3.16f1
- TrashCat game instrumented with AltTester Unity SDK v 2.0.1 from `development` branch (02.08.2023)

### Tests performed and results
- ✅ Checked after opening the instrumented app and changing the connection data in host/port/appName (in the green popup with Restart) and connecting to the AltTester Desktop app (AltServer + driver) upon reopening the instrumented app the last successful connection data is stored in the green popup and the AltServer is trying to connect to this data
- ✅ Checked that after opening the instrumented app and changing the connection data in host/port/appName (in the green popup with Restart) and connecting to the AltServer from AltTester Desktop and tests (driver) upon reopening the instrumented app the last successful connection data is stored in the green popup and the AltServer is trying to connect to this data
- ✅ Checked that after opening the instrumented app and changing the connection data in host/port/appName (in the green popup with Restart) and connecting to the AltServer started from batchmode and tests (driver) upon reopening the instrumented app the last successful connection data is stored in the green popup and the AltServer is trying to connect to this data
- ✅ Checked that after opening the instrumented app and changing the connection data in host/port/appName (in the green popup with Restart) and not having a successful connection to the AltTester Desktop app (AltServer + driver) upon reopening the instrumented app the last used connection data is not stored, only the last successful connection data in the green popup and the AltServer is trying to connect to the stored data
- ✅ Checked that after opening the instrumented app and changing the connection data in host/port/appName (in the green popup with Restart) and not having a successful connection to the AltServer from AltTester Desktop/batchmode and tests (driver) upon reopening the instrumented app the last used connection data is not stored, only the last successful connection data in the green popup and the AltServer is trying to connect to the stored data
- ✅ Checked that  if a successful connection is established only with the AltServer without connecting a driver also (AltTester Desktop app or Tests) that the last used connection data is not stored upon reopening of the instrumented app, only the data for the last successful connection with both AltServer and driver
- ✅ Checked that a successful connection with the AltServer started from AltTester Desktop/batchmode and driver (Desktop or Tests) can only be established if all three connection info match for host/port/appName (green popup, Connection Panel in Desktop/connection params in AltServer started in batchmode, AltDriver params in Tests)
- ✅ Checked that more than 2 drivers can connect at the same time to the AltServer when using the PRO plan of the AltTester Desktop
- ✅ Checked that only 2 drivers (Desktop in Connection Panel mode with tests or Desktop Inspector with instrumented app)  can connect at the same time to the AltServer when using the FREE plan of the AltTester Desktop
- ✅ Checked that there are no disconnection issues 

### Conclusion
The purpose of this ticket was achieved. The previous successful connection info is stored as expected (if the connection was made between the to the AltServer + Driver (not just the AltServer)
**Closing the ticket.**
