### ISSUE TITLE
Tap and Click on AltGameObject to send events to parents if listeners are missing

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1340]
AltGameObject.Tap or AltGameObject.Click are not sending the events to the parents.

For example `Button/Text` if you click the text normally the click event is sent to the button but in our methods are sent to the text which doesn't know what to do with it.

## Additional info

This issue is needed for alttester/AltTester-Desktop#1181

**Comment by MihaiCuc98** [comment]
### Testing environment:
- OS: Windows 10
- _AltTester Desktop_ Windows build from https://github.com/alttester/AltTester-Desktop/actions/runs/5653477481 (25.07.2023)
- TrashCat build instrumented with AltTester Unity SDK from the `development` branch (26.07.2023)
- SampleScene build instrumented with AltTester Unity SDK from the `development` branch (26.07.2023)
- Python/C# tests files using the latest AltTeste driver

### What was checked:
✔ Checked if the `Click()` and `Tap()` methods can be performed on the children of objects that have an associated click event (eg: Button/Text)

### Where I checked:
**Trashcat:**

- `Main` scene:
    - /UICamera/Loadout/OpenLeaderboard/Text
    - /UICamera/Loadout/StoreButton/Text
    - /UICamera/Loadout/MissionButton/Text
    - /UICamera/Loadout/SettingButton/Text
    - /UICamera/Loadout/StartButton/Text
- `Run` scene:
    - /UICamera/Game/DeathPopup/GameOver/Text
    - /UICamera/GameOver/Highscore/PlayerEntry/InputField/Text
    - /UICamera/GameOver/OpenLeaderboard/Text
    - /UICamera/GameOver/Loadout/Text
    - /UICamera/GameOver/RunButton/RunText
- `Shop` scene:
    - /Canvas/Background/TabsSwitch/Item/Text
    - /Canvas/Background/TabsSwitch/Character/Text
    - /Canvas/Background/TabsSwitch/Accesories/Text
    - /Canvas/Background/TabsSwitch/Themes/Text
    - /Canvas/Background/Premium/Button/Text
    - /Canvas/Background/IAPPopup/Image/Content/10_entry/Button/Text
    - /Canvas/Background/IAPPopup/Image/Content/50_entry/Button/Text
    - /Canvas/Background/IAPPopup/Image/Content/100_entry/Button/Text
- `Start` scene:
    - /Canvas/StartButton/StartText

**SampleScene**
- `Scene 1`:
     - /Canvas/TextMeshInputField/Text Area/Caret
     - /Canvas/UnityUIInputField/UnityUIInputField Input Caret

❗ for all above paths, I performed `Click()` and `Tap()` actions in both programming languages (Python and C#)


Considering this information, I will move this ticket into `Done`.
