### ISSUE TITLE
Replace indexer functionality in findobject to select the n-th object with the condition added

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1342]
For example now:
//Sphere[1]-> returns the second child of the sphere
and we want:
//Sphere[1]-> return the second object that has the name sphere

This modification will be a breaking changes for users that already have tests that uses the indexer.

We need to document very well this change and emphasize in the release notes.

**Comment by iulianatodoran** [comment]
### Testing environment
- _TrashCat_ instrumented with AltTester Unity SDK v.2.0.1 (from `development` branch on 25.07.23) in Unity v 2021.3.16f1
- AltTester Desktop v.2.0.1
- Staging documentation

### Tests performed and results
- **Checked on AltTester Desktop that**:
  - ✅ when selecting objects from the Screenshot Area with the same name and parents in the hierarchy, their Path is on the format that matches XPath which returns the n-th object that respects the Name selector
    - eg for indexed objects nested inside other indexed objects: the path `/IndustrialWarehouse01(Clone)[2]/ObjectRoot/Collectibles/Pickup(Clone)[7]` is for the 8th object named `Pickup(Clone)` that has the main parent `IndustrialWarehouse01(Clone)[2]` which is the third object named `IndustrialWarehouse01(Clone)`
  - ✅ the index `0` for an indexed object is for the first object with the same name and parents as other objects in the hierarchy
  - ✅ the index `1` for an indexed object is for the second object with the same name and parents as other objects in the hierarchy
  - ✅ the index `-1 `for an indexed object is for the last object with the same name and parents as other objects in the hierarchy
  - ✅ the index `-2` for an indexed object is for the second last object with the same name and parents as other objects in the hierarchy
  - ✅ when searching objects with the same name and parents in the Hierarchy `by PATH` using different attributes, the search returns the expected objects that satisfy the conditions in the Search
    - eg: for the Path `/IndustrialWarehouse01(Clone)[2]/ObjectRoot/Collectibles/*[@name=Pickup(Clone)][-2]` the returned object in Hierarchy is the second last object that has the attribute `@name` `Pickup(Clone)` that has the main parent the third object named `IndustrialWarehouse01(Clone)`
  - ✅ when searching an object in the Hierarchy `by PATH` with an index greater than the one that matches to the last existing one, there is no result returned
  - ✅ when searching an object in the Hierarchy `by PATH` that returns multiple objects with the same name and parents in the hierarchy, when navigating between the results, they reflect in the Path input field from the Element Info Area with the correct index 
  - ✅ Checked by using the Recorder to identify an indexed object and an assertion on a property on the component of that object that after running the test script from the recording the test passes thus validating that the indexed object is found correctly 
- **Checked in the documentation that**:
  - ✅ in the _API_ > _By-Selector_ section the indexer functionality info is included in _Searching object by PATH_
    - issue found: ❌  the `[n-th]` node refers to the `n-th` object but it should be the `n-th+1` as first `n=0` 
  - ✅ in the _API_ section > _By-Selector_ subsection the indexer functionality is included in _Examples_ along with an Important note explaining the change
    - issue found: ❌  the `[n-th]` node refers to the `n-th` object but it should be the `n-th+1` as first `n=0`
  - ✅ in the _API_ > _AltDriver_ > _Find Objects_ section there is an important note explaining the change in each command for finding objects
    - issue found: ❌  the `[n-th]` node refers to the `n-th` object but it should be the `n-th+1` as first `n=0`

### Issues found during testing
- the issues are described above in the testing scenarios and will be fixed separately by @RobertPoienar in one of his WIP PR-s

### Other notes
- there is still a need to emphasize this change in the release notes, but this is the focus of another ticket that will be implemented near the release

### Conclusion
The purpose of this ticket was achieved.

**Closing the ticket.**
