### ISSUE TITLE
Unable to launch the game twice in a row using the "Play in editor" function

### ISSUE THREAD

**Issue by rucindrea** [alttester/AltTester-Unity-SDK#1345]
## Steps to reproduce
From user: 

I am unable to launch the game twice in a row using the "Play in editor" function.
Here a very simple step to reproduce:
1. Click "Play in Editor" in the "AltTester Editor" window
2. Once the game is launched, stop the game clicking on the "Play" icon in Unity
3. Observe that "Play in Editor" is disabled

In order to enable it again, you need to either:
lose focus on Unity and go back to it  (a "Compiling C# Scripts" popup will appear)
or you can also launch the game normally and stop it, using the "Play" icon.

**Comment by RobertPoienar** [comment]
No longer reproducible in 2.0.1
