### ISSUE TITLE
[Documentation] [API > AltObject] Python and Java examples for `GetText` command contain old method

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1348]
### AR
 
In [_API > AltObject > GetText_ ](https://alttester.com/docs/sdk/latest/pages/commands.html#gettext)the examples for Python and Java contain an old method that was removed when upgrading from `v1.6.6` to `v1.7.0`:
- Python: `wait_for_element_with_text`
- Java: `WaitForObjectWithText`

### ER
 
The examples for the `GetText` command should be updated:
- for Python with `wait_for_object`
- for Java with `WaitForObject`

**Comment by iulianatodoran** [comment]
@sandraaltom The issue was found by a discord user and I assigned the `2.0.2` release label

**Comment by MihaiCuc98** [comment]
The testing session is done. What was checked:
✔ Checked the layout
✔ Checked if the tests displayed in the documentation are the tests that run in the pipeline (SDK)


Considering this information, I will move this ticket into `Done`.
