### ISSUE TITLE
[Docs - WaitForComponentProperty] The timeout and interval params are not displayed in the documentation

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1355]
## Steps to reproduce
 
1. Open https://alttester.com/docs/sdk/latest/pages/commands.html#waitforcomponentproperty
### AR
 
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/4251b180-1bc8-4e3c-8e3a-fe1dd2977665)

### ER
 
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/fb7a46b3-b72a-4080-90c1-1344f7f1e4ef)

**Comment by iulianatodoran** [comment]
✅ Checked in the Staging documentation in _API > AltObject > WaitForComponentProperty_ section that the `timeout` and `interval` params are added in the `Parameters` table with the correct and relevant information with no layout issues or typos 

![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/21714e21-746f-40b6-9f80-e914bd26335c)

Considering that, **will close the ticket**.
