### ISSUE TITLE
AltTester.Log is not created when running tests

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1357]
When running test in terminal we show in a message that we create a logfile at `./AltTester.log` but this file is nowhere to be found.

Implementation:
 1. Successfully create the file
 2. Show in the message the full path to the file

**Comment by RobertPoienar** [comment]
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/44575813/7485c935-0828-4ee2-96e3-df14655c1116)

**Comment by MihaiCuc98** [comment]
### Env setup:
- Windows 10, MacOS Big Sur 11.7.7
- AltTester Unity SDK project from the development branch (04.08.2023)
- TrashCat game with play-in editor with AltTester Unity SDK from the development branch (04.08.2023)

### What was checked:
- Checked if the AltTester.log is created at the given path when the tests are run from the cmd line (`<UnityPath>/Unity -projectPath $PROJECT_DIR -executeMethod AltTester.AltTesterUnitySDK.Editor.AltTestRunner.RunTestFromCommandLine -testsClass MyTestClass -logFile logFile.log -batchmode -quit`)
- Checked if the AltTester-Server.log is created at the given path when the TrashCat is played with `play-in editor`

Considering this information, I will move this ticket into `Done`.
