### ISSUE TITLE
Create a job that verifies if the license & copyright are added to a file and adds them in case they are missing

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1361]
Each file should have the license and the copyright added. 

## Description
 
We should create a job that:
- verifies if the license & copyright is added to the file 
- adds the license and the copyright in case it's missing

## Details
I used a PowerShell script to achieve this. Source code can be found here https://www.leniel.net/2012/08/inserting-copyright-notice-banner-in-all-source-code-files-with-powershell.html.
1. The `copyright.ps1` was created in the root directory.
2. Run the script using `.\copyright.ps1` on Windows or `pwsh copyright.ps1` on MacOS.
3. In case you get `PowerShell Script cannot be loaded because running scripts is disabled on this system error` follow the instructions from here https://www.sharepointdiary.com/2014/03/fix-for-powershell-script-cannot-be-loaded-because-running-scripts-is-disabled-on-this-system.html
4. The script will check every
a. `.cs` file in the `./Assets`
aa. `.java` file in `./Bindings~/java`
aaa. `.py` file in `./Bindings~/python`
to see if they contain the appropriate header.

For C# and Java the header should be 
```
"/*
    Copyright(C) 2023 Altom Consulting

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.
*/" + [System.Environment]::NewLine
```

For Python:
```
"""
    Copyright(C) 2023 Altom Consulting

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.
"""' + [System.Environment]::NewLine
```

5. If the files already contain the header, the header should NOT be added again.

**Comment by MihaiCuc98** [comment]
### Testing environment:
- Windows 10
- AltTesterUnity SDK project - latest dev (11.08.2023)

### What was checked:
✔ Checked if the copyright comment is displayed in all files ( C# Assets, Java and Python Bindings)

Considering this information, I will move this ticket into `done`.
