### ISSUE TITLE
[Discord Issue] The AltTester build process is including another unnecessary tests that are related to editor

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1374]
## Steps to reproduce
 
1. Add AltTester unitypackage to a project that already contains tests related to the Editor.
2. Try to make a build.
### AR
 
`Assets/Tests/PlayMode/ContextNavistance/ACCTests.cs(32,21): : The name 'AssetDatabase' does not exist in the current context` is triggered when trying to make a build
### Additional info
 

❗ Discord thread: https://discord.com/channels/744769398023127102/748145672557035625/1143499506843914250
### ER
 
The AltTester build process should ignore other tests outside of AltTests

**Comment by iulianatodoran** [comment]
### Testing environment
- Unity v 2021.3.25f1, 2022.3.8f1
- Roll-a-ball game (NIS) instrumented with AltTester Unity SDK v >2.0.2 from `development` branch (05.09.23)

### Tests performed and results
- ✅ Checked in a project (using the NIS) after adding  the AltTester unitypackage that I am able to instrument a build with no errors if that project already contains tests related to the Editor
- ✅ Checked that the previously instrumented build can connect successfully to AltTServer and to the AltTester Desktop
- ✅ Checked also that playing in the AltTester Editor window (with or without the `Keep the ALTTESTER symbol defined` option checked) works as expected with no errors in the unity console
- ✅ Checked that the tests already present in the project are displayed in the `Tests list` in the expected assembly
- ✅ Checked that the AltTester tests if created are also present in the `Tests list` in the expected assembly

### Conclusion
The issue described in the ticket is fixed.

**Closing the ticket.**
