### ISSUE TITLE
[Concurrency] Send the list of tags of the instrumented game

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1375]
## Description
 
In order to differentiate between 2 games connecting to the server having the same name, we will add tags. 

We should send on the SDK the list of all tags the instrumented game has. 

The tags should be:
- platform
- platform version
- instance-id of the device
- app id given by the server

For live update communication from AltTester Desktop we should use the app id given by the server.

**Comment by iulianatodoran** [comment]
Waiting for all SDK and Desktop concurrency-related tickets (https://github.com/alttester/AltTester-Unity-SDK/issues/1436, https://github.com/alttester/AltTester-Desktop/issues/1280) to be merged into `development` to test this.
