### ISSUE TITLE
[Documentation - USEFUL LINKS] Add links for OpenUPM and Docker Hub

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1378]
## Description
 
Since we provide the AltTester Unity SDK package in the OpenUPM platform and the AltTester Desktop Linux batchmode as a Docker image we should add the required links in the _USEFUL LINKS_ section of the Navigation Panel

**Comment by iulianatodoran** [comment]
@sandraaltom as we agreed we should add these links ASAP (after the [Linux issue](https://github.com/alttester/AltTester-Desktop/issues/1101) is fixed). I assigned the `2.0.2` label but you may change it if you consider it necessary.

**Comment by MihaiCuc98** [comment]
Checked on STAGING:
- Checked if an Open UPM link is displayed in the useful links (latest SDK docs) section and it is redirected to the official AltTester UPM page.
- Checked if a Docker Hub link is displayed in the useful links (latest SDK docs) section and it is redirected to the official AltTester UPM page.

**Conclusion:** Waiting for https://github.com/alttester/AltTester-Desktop/issues/1291 to be fixed/aborted to rechecked/reopen this issue

**Comment by MihaiCuc98** [comment]
Considering that https://github.com/alttester/AltTester-Desktop/issues/1291 is closed, I will close this ticket too.
