### ISSUE TITLE
[AltTester Editor - Build Settings] Build created with `Show popup` option unchecked still contains the popup

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1381]
### AR
 
After creating an instrumented build from the _AltTester Editor_ window using in _Build Settings_ the `Show popup` option unchecked, the build still contains the green popup when it is opened

### Additional info
 
Environment:
- AltTester Unity SDK  `v.2.0.0`, `v.2.0.1`, `v.2.0.2`

Other notes
- the issue is reproducible on the `v.2.0.0` and `v.2.0.1` versions also but it is possible to occur on older versions also

### ER
 
The  `Show popup` option should be removed, considering that one has the option in the instrumented build to move the popup, therefore this feature is no longer needed.

**Comment by iulianatodoran** [comment]
@sandraaltom I put this in `Backlog` as agreed with no release label

**Comment by sandraaltom** [comment]
Triaged Week #38, 2023.

**Comment by iulianatodoran** [comment]
**Update 11.01.24**: changed the **Expected** section in the description of the ticket as discussed with the team, concluding that the feature making the subject of this ticket is no longer needed.

**Comment by iulianatodoran** [comment]
## Testing environment
- AltTester Unity SDK from `development` branch (commit https://github.com/alttester/AltTester-Unity-SDK/commit/a523add01751df348557601a2a097ffeed9e6fc2)
- Unity 2021.3.16f1 for Windows and MacOS

## Tests performed and results
- ✅ Checked on Standalone Windows, Standalone MacOS, Android, iOS, Editor, WebGL platforms that the `Show popup` option is removed from the AltTester Editor window opened in Unity
- ✅ Checked that there are no layout issues or missing sections in the AltTester Editor window
- ✅ Checked that the main functionalities are not affected by the change from this ticket

## Conclusion
The issue was fixed and no other issues appeared in the area. Considering this, I will move the ticket to `Done`.
