### ISSUE TITLE
`AltPortForwarding` still mentioned in some examples in latest doc 2.0.2

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1386]
### Summary
There are some examples which mention class `AltPortForwarding`  in some Java and python examples. Search in code but also in palin text documentation. I could find at least on 2 pages: 
- https://alttester.com/docs/sdk/2.0.2/pages/advanced-usage.html
- https://alttester.com/docs/sdk/2.0.2/pages/get-started.html

### Steps to reproduce
1. Check the latest documentation version 2.0.2
2. Search for mentions of `AltPortForwarding`

### Relevant logs and/or screenshots
- https://alttester.com/docs/sdk/2.0.2/pages/get-started.html?highlight=altportforwarding
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62647565/8623c069-d60c-452a-bd94-087a2e3000f0)

- https://alttester.com/docs/sdk/2.0.2/pages/advanced-usage.html?highlight=altportforwarding
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62647565/c8ec12c6-a9c3-4b9a-97ea-be9198e257ca)

- https://alttester.com/docs/sdk/2.0.2/pages/advanced-usage.html?highlight=altportforwarding
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62647565/d24a7247-97fa-4c4b-9e98-e061d7326217)

**Comment by sandraaltom** [comment]
Triaged Week #38, 2023.

**Comment by MihaiCuc98** [comment]
What was checked:

- Checked if there are no more `AltPortForwading` mentions in SDK staging docs and AltTesterDesktop staging docs
- Checked if the old mentions were replaced with `AltReversePortForwarding`

Considering this information, I will close this ticket.
