### ISSUE TITLE
Link in paragraph not rendered properly in latest doc versions 2.0.1, 2.0.2

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1387]
Reproducing on versions:
- https://alttester.com/docs/sdk/2.0.1/pages/faq-troubleshooting.html
- https://alttester.com/docs/sdk/2.0.2/pages/faq-troubleshooting.html

### Relevant logs and/or screenshots
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62647565/7df6c6eb-6a1d-43ca-b718-7f73297068d7)

**Comment by sandraaltom** [comment]
Triaged Week #38, 2023.

**Comment by MihaiCuc98** [comment]
Verified as fixed in staging latest docs. Closing this issue.
