### ISSUE TITLE
[Android - Green Pop-up] The data in the green pop-up of a newly installed build remain those from a previous connection, even if the build was created with other data from unity

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1393]
## Steps to reproduce
 
1. Open the AltTrascat Project
2. Insert some predefined connection data, such as:
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/a4d6ed2f-decb-4546-9749-5ee4c893c19c)
3. Make sure that the Android phone is connected to the PC and the USB debugging is enabled and there is no Trashcat installed on it (**there should have been a Trashcat installed on the phone in the past** ).
4. Click on `Build and Run` button
### AR
 
The build is successfully created but when it is opened, the data from the green pop-up is equivalent to the data from a previous connection (not the last one)
<img src="https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/7fa7a783-2abc-45a8-89c4-12de4271f5ac" width = 300></img>
### Additional info
 
❗ This bug can be continuously reproduced on the SMA53 (Android13) phone and is not reproducible on the other two phones (Android 8 and 12). Clearing the cash memory of the Trahcat app does not help.

**Testing setup:**
- Windows 10
- Trashcat instrumented game with AltTester Unity SDK 2.0.2 released 
- Android version of the devices: 8, 12, 13
### ER
 
The data from the green pop-up of the newly installed build should be the predefined data that were inserted in the AltTesterEditor.

**Comment by MihaiCuc98** [comment]
@sandraaltom I put this ticket into the backlog because it is continuously reproducible only on my SMA53 (Android 13) phone.

**Comment by RobertPoienar** [comment]
We could add a flag in editor windows if you want to override the ip, port and appName that are in the Player pref. We can do this with the an boolean(the flag in the editor) and an UID. If the flag is true, we check to see if the UID is present in the player pref, if it's different or doesn't exist in the player pref then we use the ip, port and the appName that was set in the build and add in player pref the UID. If it's the same(meaning the application is opened again, not freshly installed) then the UID should coincide and will use the player prefs value.

But for better user experience I would also add an button/or some key combination to delete the UID or the whole player Pref(only the player pref that we set for AltTester not the whole Player pref of the application) to imitate a fresh install the next time the application is opened.

**Comment by sandraaltom** [comment]
Triaged Week #38, 2023.

**Comment by MihaiCuc98** [comment]
At the moment, there are some inconsistencies in the way this checkbox works, based on the Android version:
Android 13:
1.  Have a trashcat build already on your phone (with custom connection data)
2.  Uninstall the trashcat
3. Create a new build via AltTesterEditor:
- when the checkbox is unchecked, the new build contains an older version of connection data **(not the last one data from a successful connection)**. The newly created build should have the data from the last successful connection)

Android 8 and 12:
1.  Have a trashcat build already on your phone (with custom connection data)
2.  Uninstall the trashcat
3. Create a new build via AltTesterEditor:
- when the checkbox is unchecked, the new build contains the data from the AltTesterEditor, not the data from the last successful connection ❌(the newly created build should have the data from the last successful connection)

Considering these behaviors, I will reopen this issue.

**Comment by MihaiCuc98** [comment]
The above behavior is also reproducible for standalone builds.

**Comment by RobertPoienar** [comment]
I fixed the NIS problem, and investigated the Android problem with Mihai and I came to the conclusion it happened because corrupted data. Once we changed the app name it did not happened again.

**Comment by MihaiCuc98** [comment]
### Testing setup:
- Windows 10
- AltTester Desktop - a7bc78a 
- Roll-a-Boll project (NIS) with the following submodule: AltTesterUnity SDK from the latest dev (16.10.2023)
- Trashcat project (OIS) with the following submodule: AltTesterUnity SDK from the latest dev branch (16.10.2023)

### Small Dictionary:
Connection Data = the connection data from the green pop-up of the instrumented game
Checkbox = `Reset connection data` checkbox

### What was checked:
✔ Checked if there are no errors when the `Play in editor` is used, no matter what Input System is used.
✔ Checked if there are no errors when a `Standalone` build is created, no matter what Input System is used.
✔ Checked if there are no errors when an `Android` build is created, no matter what Input System is used.
✔ Checked if the connection data is changed with the data from the Editor (checked with default data and custom data) when the build is created (`Buily only`, `Build and Run`, `Play in Editor`) with `Reset Connection data` checked.
✔ Checked if the connection data is not changed when the build is created with `Build and Run`/`Build Only` (checkbox unchecked) and, in the case of Android, if there was a previous apk installed on it
✔ Android related: Checked if the connection data are reset when the build is created with `Build and Run` (checkbox unchecked) if the existing app is uninstalled before building a new app. (**this happens because the PlayerPrefs are deleted when the app is uninstalled**).
✔ Android related: Checked if the uninstalling ways (by phone or adb) will not affect the results from the previous check.
✔ Android related: Checked if changing the location of the APK before installation will not affect the results from the previous checks

### Findings:
- https://github.com/alttester/AltTester-Unity-SDK/issues/1414
Considering this information, I will move this ticket into `Done`.
