### ISSUE TITLE
Add ® to every AltTester mentioning

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1399]
## Description
 
Considering that [AltTester is now a registered trademark](https://euipo.europa.eu/eSearch/#details/trademarks/018858398) we need to make sure we add `®` in all places where is mentioned

We should make sure that the change is made in all places:
- [x] all documentation files (including relevant screenshots)
- [x] `README.md` files
- [x] version in AltTester Prefab
- [ ] Bindings websites (needs user rights for each website to perform modifications > to check who has these rights)

**Comment by iulianatodoran** [comment]
@sandraaltom

**Comment by sandraaltom** [comment]
Triaged Week no. 39, 2023.

**Comment by iulianatodoran** [comment]
@MihaiCuc98 FYI: The `alttester-with-cloud.md` file was not updated with `®` because there is another [PR](https://github.com/alttester/AltTester-Unity-SDK/pull/1394) WIP where the entire section is changed and it will be added there

**Comment by MihaiCuc98** [comment]
The testing session is done. 
### Testing setup:
- Windows 10
- AltTester Unity SDK project with the latest changes from dev branch (10.10.2023 - 10:00)
- Trashcat Android made with the latest changes from dev branch (10.10.2023 - 12:00)

### What was checked:
✔ Checked if the registered trademarks were added for AltTester, AltTester Desktop, AltTester Unity SDK in all the AltTester Unity SDK project (excepting `alttester-with-cloud.md`)
✔ Checked if the trademark is displayed properly in the AltTester Prefab (checked with `play in editor` and with Android build)
✔ Checked if the trademark is displayed properly for AltTester Unity SDK in the Nuget readme

Considering this information, I will move this ticket into `Done`
