### ISSUE TITLE
[Investigate] How big is the Lego Microgame app in order to be included in SDK

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1401]
## Description
 
Considering the https://github.com/alttester/AltTester-Unity-SDK/issues/1283 issue, we should be able to add an automated test in bindings for this case. In order to do this, we can:
- import the Lego Microgame in our SDK
- create a new scene where we can replicate the behavior

**Comment by sandraaltom** [comment]
Triaged Week no. 40, 2023.

**Comment by rucindrea** [comment]
We can work on improving our tests on different games separately, without including this in the sample game.
