### ISSUE TITLE
[Input] Click action on an button that destroys itself on click raises an error

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1404]
This was noticed on a client project. Happens because we changed the clicking event to be executed in hierarchy instead of just the object and the way Unity wrote that method it tries to access the gameobject after the object was deleted.
Also a problem that we have, is that we don't check correctly if the object is deleted. We are using `gameobject == null` but this doesn't work if the object is deleted but the GC didn't clean it yet. A solution I found on the internet is to use `gameobject ?? false `

## Steps to reproduce
 
- Create a script that when the object is clicked, the object will be destroyed
- Create a test to click on that object
- See logs

### Additional info

I fixed the issue on the client project.

**Comment by sandraaltom** [comment]
Triaged Week no. 40, 2023.

**Comment by MihaiCuc98** [comment]
### Setup:
- Windows 10, Unity 2021.3.19f
- AltTesterUnity SDK project with the latest changes from dev branch (15:40)

### What was checked
✔ Checked if the `TestClickDestroyButton` from `Assets\Examples\Test\Editor\Driver\TestForScene5KeyboardAndMouseInput.cs` is passing locally
✔ Checked if the test passes if the timeout param of the `Destroy` method is deleted from the `Destroy` object.

Considering this information, I will move this ticket into `Done`
