### ISSUE TITLE
[Input] Tap/Click on coordinates not working for 2D objects

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1419]

**Comment by MihaiCuc98** [comment]
### Testing setup:
- Windows 10
- AltTester Desktop 2.0.2 released
- SampleScenes standalone instrumented with https://github.com/alttester/AltTester-Unity-SDK/pull/1420/commits/7252029aeba5c201305e51ba8089c3e65ba8c621

### What was checked:
- Checked locally if the tests from the pipeline are successfully executed
- Checked if the `Click/Tap/Hold/Swipe` actions are successfully executed through the Screenshot Area
- Checked if the `Click/Tap/Hold/Swipe` methods are successfully executed in a test made with recorder(C#, Python and Java(extra, not in the recorder))

Considering this information, we can close this ticket.
