### ISSUE TITLE
Update docs for concurrency features

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1421]

**Comment by iulianatodoran** [comment]
We should inform the users somewhere in the documentation that older SDK versions (working with the old AltServer) will only work with the new AltServer in single mode, but not in parallel mode

**Comment by iulianatodoran** [comment]
## Testing environment
- Staging documentation updated from 06.02.2024

## Tests performed and results 
- ✅ Checked in the _Advanced Usage_ section that there is a subsection dedicated to executing the tests concurrently named _Execute tests concurrently_
- Checked in the _Execute tests concurrently_ subsection that
  - ✅ all the required and correct information is included about the use of multiple tags, their names, and how to use them
  - ✅ there are examples for each language with the tags used in the AltDriver constructor 

    ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/8a1bad7e-256a-4ab0-bd99-b1d989c473c0)

  - ✅ the examples can be used successfully in tests (checked the one with environment variables and considering that the one using the `--platform` command line parameter was already checked by the developer, did not check it also) 
  - ✅ there is a warning for the older SDK version (as mentioned in my [previous comment](https://github.com/alttester/AltTester-Unity-SDK/issues/1421#issuecomment-1900302122))
  - ✅ there are no typos or layout issues
- ✅ Checked in the _API_ section that new parameters for tags are added in the AltDriver class with correct information and no typos

    ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/3380914d-7aca-45a0-aeb7-e8c4e4c848d6)

## Conclusion
Considering the above information **I will close this ticket**.
