### ISSUE TITLE
[Concurrency] Fix bugs listed in test planning

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1436]
https://docs.google.com/spreadsheets/d/1WO7flPge9mCt7gxHvGtMR9wcsptvQlGE0216P-x94LU/edit#gid=1234426889

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Unity-SDK/issues/1375 and https://github.com/alttester/AltTester-Desktop/issues/1280 

Considering this, I **will close this ticket**.
