### ISSUE TITLE
[BrowserStack] Some Python tests fails on BrowserStack but pass on our real devices

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1438]
## Steps to reproduce
 
1. Run Python tests from Bindings on a real device from Browserstack
### AR
 
Some tests are constantly failing on BrowserStack(`NIS tests` and some tests from `scene01`). Please take a look at the following test reports:
- iOS: https://drive.google.com/drive/folders/1FbknMchnB72OcymtHqEtNHy5AlMbPIIn
- Android: https://drive.google.com/drive/folders/1FbknMchnB72OcymtHqEtNHy5AlMbPIIn
### ER
 
The behavior of the tests running in the BrowserStack should be similar to the way they run on our real devices.

**Comment by sandraaltom** [comment]
Triaged Week no. 47.

**Comment by MihaiCuc98** [comment]
The testing session is done. 

### Setup:
- Windows 10
- BrowserStack App automate environment (android: 12.0-> Google Pixel 6, ios: 16 -> iPhone 14)
- AltTester Unity SDK from branch `1316-add-a-ci-job-for-running-tests-on-browserstack-with-ios` (up to date with dev branch (21.12.2023))

### Checks:
- Checked if the Android tests are successfully run with no failures (2 attempts using github Actions)
- Checked if the iOS tests are successfully run with no failures (2 attempts using github Actions)
    - ❌some tests are still failing (`test_get_static_property` and `test_wait_for_component_property_assembly_not_found`) but I logged a separate ticket for that.

### Findings:
- https://github.com/alttester/AltTester-Unity-SDK/issues/1455

Considering this information, I will move this ticket to `Done`.
