### ISSUE TITLE
Remove Unity Ads

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1441]
## Description
 
The goal of this ticket is to remove unity ads from the project's manifest.json

**Comment by iulianatodoran** [comment]
## Testing environment
- OS: Mac OS Big Sur v 11.7.10, iPhone 6
- Unity v 2021.3.16f1
- Xcode v 13.2.1 (13C100)

## Tests performed and results
 - ✅ Checked that I can instrument with no errors an iOS build in Unity and Xcode for the _sampleGame_ from the AltTester Unity SDK repo from the `development` branch 

## Conclusion
Closing the ticket as the build error referring to Unity adds is not reproducible anymore.
