### ISSUE TITLE
`Input string was not in a correct format` exception thrown when trying running C# tests that do not connect to AltServer

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1444]
## Steps to reproduce
 
1. In a `C#` test initialize the AltDriver with the parameter `connectTimeout: 10` (to catch the exception earlier)
2. Start running the test (eg. in Unity) without having a connection started with the AltServer
3. Check the thrown exception in the console

### AR
 
Exception thrown :
```
OneTimeSetUp: System.FormatException : Input string was not in a correct format.

UnityEngine.Debug:LogError (object)
AltTester.AltTesterUnitySDK.Driver.Logging.UnityTarget:Write (NLog.LogEventInfo)
NLog.Targets.Target:Write (NLog.Common.AsyncLogEventInfo)
NLog.Targets.Target:WriteAsyncThreadSafe (NLog.Common.AsyncLogEventInfo)
NLog.Targets.Target:WriteAsyncLogEvent (NLog.Common.AsyncLogEventInfo)
NLog.LoggerImpl:WriteToTargetWithFilterChain (NLog.Targets.Target,NLog.Filters.FilterResult,NLog.LogEventInfo,NLog.Common.AsyncContinuation)
NLog.LoggerImpl:Write (System.Type,NLog.Internal.TargetWithFilterChain,NLog.LogEventInfo,NLog.LogFactory)
NLog.Logger:WriteToTargets (NLog.LogEventInfo,NLog.Internal.TargetWithFilterChain)
NLog.Logger:WriteToTargets (NLog.LogLevel,System.IFormatProvider,string)
NLog.Logger:Error (string)
AltTester.AltTesterUnitySDK.Editor.AltTestRunListener:TestFinished (NUnit.Framework.Interfaces.ITestResult)
NUnit.Framework.Internal.Execution.CompositeWorkItem:SkipChildren (NUnit.Framework.Internal.TestSuite,NUnit.Framework.Interfaces.ResultState,string)
NUnit.Framework.Internal.Execution.CompositeWorkItem:PerformWork ()
NUnit.Framework.Internal.Execution.WorkItem:RunTest ()
NUnit.Framework.Internal.Execution.WorkItem:Execute ()
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher:Dispatch (NUnit.Framework.Internal.Execution.WorkItem)
NUnit.Framework.Internal.Execution.CompositeWorkItem:RunChildren ()
NUnit.Framework.Internal.Execution.CompositeWorkItem:PerformWork ()
NUnit.Framework.Internal.Execution.WorkItem:RunTest ()
NUnit.Framework.Internal.Execution.WorkItem:Execute ()
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher:Dispatch (NUnit.Framework.Internal.Execution.WorkItem)
NUnit.Framework.Internal.Execution.CompositeWorkItem:RunChildren ()
NUnit.Framework.Internal.Execution.CompositeWorkItem:PerformWork ()
NUnit.Framework.Internal.Execution.WorkItem:RunTest ()
NUnit.Framework.Internal.Execution.WorkItem:Execute ()
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher:Dispatch (NUnit.Framework.Internal.Execution.WorkItem)
NUnit.Framework.Internal.Execution.CompositeWorkItem:RunChildren ()
NUnit.Framework.Internal.Execution.CompositeWorkItem:PerformWork ()
NUnit.Framework.Internal.Execution.WorkItem:RunTest ()
NUnit.Framework.Internal.Execution.WorkItem:Execute ()
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher:Dispatch (NUnit.Framework.Internal.Execution.WorkItem)
NUnit.Framework.Internal.Execution.CompositeWorkItem:RunChildren ()
NUnit.Framework.Internal.Execution.CompositeWorkItem:PerformWork ()
NUnit.Framework.Internal.Execution.WorkItem:RunTest ()
NUnit.Framework.Internal.Execution.WorkItem:Execute ()
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher:Dispatch (NUnit.Framework.Internal.Execution.WorkItem)
NUnit.Framework.Internal.Execution.CompositeWorkItem:RunChildren ()
NUnit.Framework.Internal.Execution.CompositeWorkItem:PerformWork ()
NUnit.Framework.Internal.Execution.WorkItem:RunTest ()
NUnit.Framework.Internal.Execution.WorkItem:Execute ()
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher:RunnerThreadProc ()
System.Threading.ThreadHelper:ThreadStart ()
```

### Additional info
 

- It seems the reason for this error is that something is missing from the code line `throw new ConnectionException(string.Format("Connection closed by AltServer with reason: {}.", this.closeReason));` from `AltTester-Unity-SDK\Assets\AltTester\Runtime\AltDriver\Communication\DriverWebSocketClient.cs`
-  the issue reproduces with AltTester Unity SDK v.2.0.2 (released) and also the dev version

SS
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/0e1778d2-d6a0-4b58-b9ff-1c9d5c319530)

### ER
 
- Another exception should be thrown when unable to connect the tests with the AltServer: `OneTimeSetUp:AltTester.AltTesterUnitySDK.Driver.ConnectionException: Connection closed by AltServer with reason: An exception has occurred while connecting...`
- the code line specified in the **Additional info** should contain an `0` between `{}`: `throw new ConnectionException(string.Format("Connection closed by AltServer with reason: {0}.", this.closeReason));`

### Additional info
 

SS
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/f7415aae-da6f-4f5e-a91c-019b41dc93df)

**Comment by iulianatodoran** [comment]
@sandraaltom I'll put this ticket in `2.1` release because it is a super easy fix

**Comment by MihaiCuc98** [comment]
Currently, the exception that is triggered when the tests try to connect to the server and fail is based on connectTimeout:
- connectTimeout >23s: `System.InvalidOperationException : A series of reconnecting has failed.`
- connectTimeout <24s: `ConnectionException : Connection closed by AltServer with reason: An exception has occurred while attempting to connect..`

Moreover, the error message of the c# driver in this situation is different from the messages of the other drivers (`ConnectionTimeoutException: Failed to connect to AltTester on host: 127.0.0.1 port: 13000.`)

Considering this information, I will reopen this issue.

**Comment by MihaiCuc98** [comment]
### Testing setup:
- AltTester-Unity-SDK project with latest changes from dev branch (04.01.2024)

### What was checked:
✔ Checked if the newly triggered exception in this situation is `ConnectionException`
❌ Checked if the message of the exception is similar with the messages from other programming languages (Python and Java) - #1463 
❌ Checked if the exception is independent of `connectTimeout` #1463 

### Findings:
- #1463 
- #1462 

Considering this information, I will close this ticket.

**Comment by wbwxshao** [comment]
Hello! @iulianatodoran 
I see you mentioned you will put this in the 2.1 version: https://github.com/alttester/AltTester-Unity-SDK/issues/1444#issuecomment-1845579151
But the latest release is 2.03 and we are facing this issue. Could you please help us where we can find the changes you made and use that? Thanks!

**Comment by iulianatodoran** [comment]
@wbwxsha, the changes are in this PR: https://github.com/alttester/AltTester-Unity-SDK/pull/1446/files. The solution was also given in the _Expected result_ section in the description of the ticket.

**Comment by wbwxshao** [comment]
@iulianatodoran 
Thanks for your reply. But I didn't see any solution given in the expected result? Please advise.

![image](https://github.com/alttester/AltTester-Unity-SDK/assets/44184324/1b167389-0d42-470a-94b0-ab2cf8887deb)
