### ISSUE TITLE
[Some python tests fail on iOS] test_get_static_property and test_wait_for_component_property_assembly_not_found fail on iOS

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1455]
## Steps to reproduce
 
1. Open the AltTesterDesktop
2. Open the [sampleGame.ipa](https://drive.google.com/drive/folders/1KrNgALDoaOlAcW25x8DhV-DOgVAlo9RH) on iOS device
3. Connect it to the AltServer
4. Open the AltTester-Unity-SDK
5. Start the tests from python bindings (run command `pytest Bindings~/python/tests/integration `)
### AR
 
`test_get_static_property` and `test_wait_for_component_property_assembly_not_found` fail on iOS. Please take a look at the following errors:
![image (28)](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/4d168ea8-9e5d-465b-918e-81d7ad6ffed5)
![image (29)](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/567854bd-cda6-4342-b0bf-8050c3490289)

### ER
 
The tests should be commented on or adjusted so that there are no more errors when running.

**Comment by sandraaltom** [comment]
Triaged Week no. 2. Not prioritised for next release.

**Comment by iulianatodoran** [comment]
The tests are marked in their respective scripts as `@pytest.mark.iOSUnsupported`.

Considering this I will close this ticket.
