### ISSUE TITLE
[Input] Move mouse is not calling OnMouseDrag

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1457]
I added the call for invoking OnMouseDrag for the following: MoveTouch, MoveMouse and Swipe. The requirement for this to trigger is to be holding down an object with a collider.

Added a demo scene where this is used and tests for each actions

**Comment by iulianatodoran** [comment]
This ticket was tested before the v `2.0.3` release and was merged later in `development`.

**Closing the ticket**.
