### ISSUE TITLE
[Concurrency] Java AltDriver tags issue

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1458]
1. On Java when I connected a test with specific tags in AltDriver, the specific tags were not parsed when running the test on an Android, only the default ones.

- The tags used in the `TestHelper.java` script:
```
public static AltDriver getAltDriver() {
        return new AltDriver("192.168.1.104", TestsHelper.getAltDriverPort(), true, 60, "sg", "Android",
                "Android OS 12 / API-31 (SKQ1.210908.001/V13.0.6.0.SFNEUXM)", "637ee113e8de943a538c734003320dac",
                "unknown");
    }
```

- See the logs from AltServer where the tags are the default ones:
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/b0ea2afa-c038-4019-a68f-1cf12533ee84)

2. Check also the conflicts on this branch

_Originally posted by @iulianatodoran in https://github.com/alttester/AltTester-Unity-SDK/issues/1440#issuecomment-1864481828_

**Comment by iulianatodoran** [comment]
## Testing environment
- sampleGame builds (Standalone, Android, WebGL, iOS) instrumented with AltTester Unity SDK from `development` branch (17.01.24)
- AltTester Desktop from `development` branch  (15.01.24 - commit `38c1c60`) 

## Tests performed and results
- ✅ Checked that the Java tests successfully connect with AltServer when using specific tags and that the AltServer logs show the expected tags that were parsed in the test script
- ✅ Checked that the Java tests successfully connect with AltServer when using default tags nd that the AltServer logs show the default tags that were parsed in the test script
- ✅ Checked that the Java tests don't connect with AltServer when using unmatched tags, the test logs show the `No app connected that has the given tags.` error and that the AltServer logs show the expected tags that were parsed in the test script

## Conclusion
Considering the above information **I will close this ticket.**.
