### ISSUE TITLE
[Python Driver] ConnectionTimeoutError error is triggered instead of NoAppConnectedException when no game is connected to the server

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1462]
## Steps to reproduce
 
1. Open the AltTesterDesktop on localhost (127.0.0.1:13000)
2. Open the Python Bindings and go to the `tests` folder
3. run `pytest` command in terminal (you should have pytest installed on your pc)
### AR
 
The tests fails with `ConnectionTimeoutError: Failed to connect to AltServer host: 127.0.0.1 port: 13000`.
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/43df61e0-b1b1-49ae-b498-44cb74942ca5)

### Additional info
 
❗This behavior is also encountered using a 2.0.2 AltTester-Driver (python)
Setup:
- AltTesterDesktop made with dev branch (21.12.2023)
- AltTester Unity SDK project from latest dev (04.01.2023)
- python project that uses AltTesterDriver 2.0.2 released
### ER
 
Based on how it is implemented in C# and Java, the error triggered in this situation should be `NoAppConnectedException`. Example from c#:
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/a373df5d-bfff-49f6-abb5-fd5487243cad)

**Comment by sandraaltom** [comment]
Triaged Week no. 2.

**Comment by MihaiCuc98** [comment]
At the moment, the behavior is reproducible using Java driver. 
Considering this information, I will reopen this ticket.

**Comment by MihaiCuc98** [comment]
I will close this ticket because the issue is not reproducible on Java. It was a VS code-related error with the Java runner. After fixing it, the issue is fixed. 

Checks:
✔ Checked if the `No app connected that has the given tags.` error is triggered when the Bindings(C#, Java, Python) tries to connect to an unexisting game.

I will close this ticket.
