### ISSUE TITLE
[Concurrency] Connection with AltServer established immediately after changing `Host`/`Port` on Green Popup without restarting the connection data

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1464]
## Steps to reproduce
 
1. **Open an instrumented app** and use a `Host`/`Port` that should not match the `Host`/`Port` the machine running the AltServer is using
2. **Start AltServer** from AltTester Desktop
3. **Change the `Host`/`Port`** in the instrumented app with matching data for the started AltServer
4. **Check if the connection with the AltServer is established**, making sure not to click the `Restart` button from the app's Green Popup

### AR
 
The connection with the AltServer is established even though the `Restart` button was not clicked on the Green popup

### Additional info
 

Environment
- sampleGame instrumented with AltTester Unity SDK from `development` branch (05.01.24) - using the concurrency features
- AltTester Desktop from `development` branch (08.01.24) - using the concurrency features

Notes
- the issue is not reproducible with the release version of AltTester Unity SDK and AltTester Desktop

### ER
 
The connection with the AltServer should not be established until the `Restart` button is clicked

**Comment by iulianatodoran** [comment]
@sandraaltom

**Comment by sandraaltom** [comment]
Triaged Week no. 2.

**Comment by iulianatodoran** [comment]
## Testing environment
- sampleGame build instrumented with AltTester Unity SDK from `development` branch (17.01.24)
- AltTester Desktop from `development` branch  (15.01.24 - commit `38c1c60`) with updated `AltServer.dll` from the project's `master` branch

## Tests performed and results
- ✅ Checked that by following the steps in the ticket the issue is not reproducible anymore
- ✅ Checked that after stopping and restarting the AltServer from the Desktop app the message in the green popup (having matching connection data) is the expected one:
  - ✅ after stopping the AltServer the message in the game's green popup is `Waiting to connect to AltServer...`
  - ✅ after restarting the AltServer the device connects to the AltServer and the message in the game's green popup is `Connected to AltServer...`** with a new appId 
- ✅ Checked that I can connect the game connected with the AltServer with the Desktop app in Inspect mode
- ✅ Checked that I can connect the tests for the  game connected with the AltServer 

## Conclusion
Considering the above information **I will close this ticket.**.
