### ISSUE TITLE
[Concurrency] [Green Popup] Tags name inconsistent with those used in the AltDriver and AltTester Desktop

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1468]
### AR
 
The tags displayed in the Green Popup of the instrumented build are inconsistent with those used in the AltDriver and AltTester Desktop, as you can see below in _Additional info_

### Additional info
 

Environment
- build instrumented with AltTester Unity SDK from `development` branch (05.01.24)
- AltTester Desktop from `development` branch  (10.01.24)

Tags
- in Green Popup: `app name`, `platform`, `platform version`, `device id`, `app id`
- in AltDriver: `appName`, `platform`, `platformVersion`, `deviceInstanceId`, `appId`
- in Alttester Desktop: `AppName`, `Platform`, `PlatformVersion`, `DeviceInstanceId`, `AppId`

### ER
 
The tags displayed in the Green Popup of the instrumented build should be consistent with those used in the AltDriver and AltTester Desktop - in the Green Popup they should be named: `appName`/`AppName`, `platform`/`Platform`, `platformVersion`/`PlatformVersion`, `deviceInstanceId`/`DeviceInstanceId`, `appId`/`AppId`

**Comment by iulianatodoran** [comment]
@sandraaltom issue found while testing the concurrency features

**Comment by sandraaltom** [comment]
Triaged Week no. 2. 
Easy and fast solution: to change the name of the variables.

**Comment by iulianatodoran** [comment]
## Testing environment
- OS for Desktop app: Windows 10, MacOS Big Sur 11.7.10
- AltTester Desktop from `development` branch  (15.01.24 - commit `ff1bc0e`)
- game builds instrumented with AltTester Unity SDK from `development` branch (15.01.24)

## Tests performed and results
- ✅ Checked on the _Connection Page_ in AltTester Desktop and the Green Popup from the instrumented build that the names of the tags are consistent with those used in the AltDriver (for C# and Java), with the tags's names being: `appName`, `platform`, `platformVersion`, `deviceInstanceId`, `appId`

  AltTester Desktop
  ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/87608e1e-ba27-4ab2-826a-25747fbec351)

  Instrumented build
  ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/4a861d02-327d-44a7-bcf8-f8bb4d92bb01)
    
- ✅ there are no layout/UI inconsistencies/typos
- ✅ there are no theme inconsistencies 

## Conclusion
Considering the above information **I will close this ticket.**
