### ISSUE TITLE
WebGL build created in Unity 2021 and 2022 does not launch on Safari

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1475]
## Steps to reproduce
 
1. In a 2021/2022 Unity version **Instrument a WebGl build with AltTester Unity SDK** (using the [recommendations](https://alttester.com/docs/sdk/latest/pages/get-started.html#instrument-your-app-with-alttester-unity-sdk) from the documentation)
2. **Launch the WebGl build in the Safari browser** using eg. the _Live Server_ extension from VSCode

### AR
 
The build cannot be launched on the Safari browser

### Additional info
 
Environment
- WebGL game build instrumented with AltTester Unity SDK from `development` branch (15.01.24)
- Safari Version `16.6.1 (16615.3.12.11.5, 16615)` (on `macOS Big Sur v 11.7.0`)
- Unity versions for instrumenting: `2021.3.16f1`, `2022.3.17f1`, `2023.2.4f1`
- AltTester Desktop from `development` branch  (12.01.24 - commit `ff1bc0e`)

Screenshot 
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/6e971df7-ac14-4776-9992-67e73b523c8c)

Notes
- the GoalKeeper build created in  `2023.2.4f1` can be launched in the Safari browser successfully
- issue found while testing https://github.com/alttester/AltTester-Unity-SDK/issues/1429

### ER
 
Either:
- The WebGL builds created with Unity 2021/2022 versions should be successfully launched in the Safari browser, or
- Document the problem if it is not AltTester-related

**Comment by iulianatodoran** [comment]
Triaged Week no.3. Not prioritised for next releases

**Comment by iulianatodoran** [comment]
We should document this problem if turns out is not AltTester related

**Comment by iulianatodoran** [comment]
@robert-altom please include the necessary info in the SDK documentation

**Comment by robert-altom** [comment]
Depending on what version of Unity are you using the build will not lunch on Safari <17.0, the build works on Safari 17.0. (The latest safari). But the same error happens for a build without the SDK. 

We decided to close this issue without updating the documentation, because if you can run your project on Safari without the SDK, it will work with the SDK too.
