### ISSUE TITLE
[MacOS] Instrumented app connected with Desktop's Inspect mode disconnects shortly from the remote AltServer started from batchmode

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1484]
## Steps to reproduce
 

1. **Start AltServer remote on MacOS (batchmode)**
2. **Start Desktop on the Windows local machine on `Remote AltServer` tab**, with matching connection data for the remote AltServer
3. **Connect an instrumented app with the remote AltServer**
4. **Connect the instrumented app in the Desktop's Inspect mode on the local machine**
5. Wait about 1.5 min and **check the connection status of the instrumented app with the AltServer and the message from green popup in the instrumented app**

### AR
 
The instrumented app disconnects from the AltServer, but in the green popup of the instrumented app the message is still `Connected to AltServer on ... Driver connected`

### Additional info
 

Environment
- sampleGame build instrumented with AltTester Unity SDK from `development` branch (15-18.01.24)
- AltTester Desktop for Windows, MacOS GUI and batchmode from `development` branch  (18.01.24 - commit `38c1c60`)

Screenshots
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/ade1027a-3ab9-4551-86ed-dcd6a81f4fc0)
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/9bed8594-3650-436e-a152-6478b327638b)

Notes on the behavior
- the behavior is still reproducible with the build from the `0dd1964` commit from 15.01.24 so it might be related to it, as it seems that it didn't reproduce before
- the issue is not reproducible when using the AltTester Desktop batchmode started on Windows

### ER
 
The instrumented app should not disconnected unintended from the AltServer and the message from the green popup should reflect the correct connection status.

**Comment by iulianatodoran** [comment]
@RobertPoienar can you please take a look into this issue, as we agreed on a daily status a few days ago? 

(cc @sandraaltom)

**Comment by RobertPoienar** [comment]
Triaged Week no. 5, 2024. Prioritized for next releases.

**Comment by iulianatodoran** [comment]
The issue is still reproducible with this setup:
- MacOS Big Sur v 11.7.10 for running the AltTester Desktop in batchmode for remote connection
- sampleGame build instrumented with AltTester Unity SDK from `development` branch (15.02.24)
- AltTester Desktop for MacOS from `development` branch  (15.02.24 - commit `76cce01`)

**Comment by iulianatodoran** [comment]
Also tried it on a more powerful Mac, and experienced connection issues with this setup:

## Environment
- Mac Studio 2022 (from the office with IP ending in `36`)  for running the AltTester Desktop in batchmode for remote connection
- sampleGame iOS build instrumented with AltTester Unity SDK from `development` branch (15.02.24) - opened on an iPhone 8 with iOS 15.5
- AltTester Desktop from `development` branch  (15.02.24 - commit `76cce01`)

## Testing observations
- after some Hierarchy inspection and some multiple scene changing (not very fast) at some point the Desktop app is stuck and cannot perform any scene change or select objects
- then (can be after a few seconds or even minutes) the Desktop driver disconnects with a different error than the one described in the ticket so it might be a different behavior but still be related
- also after disconnection the app was not displayed on the device list and after restarting the remote connection  it appeared but with the warning for older version and after reconnection the Live Update does not work, as if the SDK would be of an older version 
  - only after restarting the AltServer the status was displayed as `Ok` and the _Live Update_ `ON` was functional

  ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/551ae004-5b2b-4eb4-acd1-50732ef1f54e)

- from 5 disconnections only once the error occurred as in the above screenshot and also the Live Update problem, in the other cases there was no error in the AltServer logs and solely the logs for `Driver disconnected`

**Comment by iulianatodoran** [comment]
To be tested after https://github.com/alttester/AltTester-Unity-SDK/pull/1515 and https://github.com/alttester/AltServer/pull/69 are merged

**Comment by iulianatodoran** [comment]
## Testing environment
- OS for running the AltTester Desktop remotely in batchmode: MacOS Big Sur v 11.7.10 (older with lower performance), Mac Studio 2022 (newer with better performance from the office with IP ending in `36`) 
- OS for running the AltTester Desktop GUI: Windows 11
- sampleGame Standalone Windows/Android/iOS/WebGL builds instrumented with AltTester Unity SDK from `development` branch (29.02.24)
- AltTester Desktop from `development` branch  (29.02.24 - commit `598f416`)

## Tests performed and results
- ✅ Checked that by following the steps described in the ticket the issue is not reproducible anymore: the app and Desktop driver do not disconnect from the remote Altserver
- ✅ Checked that the Desktop driver nor the game disconnect from the remote AltServer after performing multiple scene changes, inspections in the Screenshot Area and Hierarchy, or using mouse actions in the Screenshot Area
- ✅ Checked that the behaviors described in the above comment do not occur on any tested machine 

##  Conclusion
Considering the above information **I will move this ticket into `Done`**.
