### ISSUE TITLE
App put in background not reconnecting to AltServer after put back on focus and popup still showing `Connected...`

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1487]
## Prerequisites
- ❗ On the Android/iOS device make sure to have the option `Battery saver`/`Power saving` selected

## Steps to reproduce
 
1. **Start the AltServer from AltTester Desktop in batchmode**
2. **Open a mobile instrumented build with matching connection data** 
4. After the connection is established, **put the app in the background**
5. **Wait 4 minutes until the app disconnected from the AltServer** (check the logs)
6. **Bring the app back in focus** and **check the connection status on the AltTester Popup and the AltServer logs**

### AR
 
After the app is brought back on focus, the AltTester popup shows that the app is `Connected...` but with the old `appId` for the former connection with the AltServer and the AltServer logs show that the app did not reconnect.

### Additional info
 
Environment
- sampleGame Android/iOS build instrumented with AltTester Unity SDK from `development` branch (23.01.24)
- AltTester Desktop from `development` branch (22.01.24 - commit `341ccc1`)

Screenshots
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/b5ff6cf9-af02-4d2b-ac57-8c1c8bf51f50)

Other notes
- the issue is not reproducible with the AltTester Desktop in GUI mode
- only after restarting the connection data from the AltTester popup the app can reconnect to the AltServer
- if the prerequisite described at the beginning of this ticket is not complied with the app will not disconnect after being put in the background 
- issue found while testing https://github.com/alttester/AltTester-Unity-SDK/issues/1482

### ER
 
After the app is brought back on focus, the AltTester popup should show that the app is `Connected...` with a new `appId` for the new connection with the AltServer and the AltServer logs should show that the app reconnected.

**Comment by RobertPoienar** [comment]
Triaged Week no. 5, 2024. Not prioritized for next releases.

**Comment by iulianatodoran** [comment]
Still reproducible with v `2.1.`0 but the AppId is expected to remain the same until the connection data is restarted.

**Comment by iulianatodoran** [comment]
The issue is not reproducible anymore with v `2.2.0`  and the AppId is the same, as expected, after the `2.1.1` release.

Closing the ticket.
