### ISSUE TITLE
[CoinCollector] `TestPlayerJumpsOnPressKey()` test fails sometimes 

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1491]
## Prerequisuites
- clone the CoinCollector project from here: https://github.com/alttester/EXAMPLES-NewInputSystem--CoinCollector-CSharp
- in `Assets\Editor\Tests\AltTester_NIS_Tests.cs` modify the `TestPlayerJumpsOnPressKey()` test to repeat 5 times (with `[Repeat(5)]`)
- instrument a Standalone build 

## Steps to reproduce
 
1. Start the instrumented game and connect it to the AltServer from AltTester Desktop with default connection data
2. In the unity project repeteat the running of the `TestPlayerJumpsOnPressKey()` test until it fails

### AR
 
Sometimes (at the first repetition or not)  the test fails because the player does not jump

### Additional info
 
Environment 
- build instrumented with AltTester Unity SDK from `development` branch (January 2024) or released version `2.0.2`
- AltTester Desktop from  `development` branch (January 2024)

Screenrecording

https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/388ce46f-d174-4c16-98cd-e554b59e0881

Test that fails
```
[Test]
    [Repeat(5)]
    public void TestPlayerJumpsOnPressKey()
    {
        altDriver.LoadScene("GameScene");        
        Thread.Sleep(1000);

        // move the player down until he arrives at the coin
        var playerPosition = altDriver.FindObject(By.NAME, "Player");
        var coinPosition = altDriver.FindObject(By.NAME, "SpawnPoint (1)");
        altDriver.KeyDown(AltKeyCode.DownArrow);
        while(playerPosition.worldZ - 3 > coinPosition.worldZ) {
            playerPosition = altDriver.FindObject(By.NAME, "Player");
        }
        altDriver.KeyUp(AltKeyCode.DownArrow);

        // jump to collect the coin using press key on left click
        altDriver.PressKey(AltKeyCode.Mouse0);
        
        // verify that the coin was collected
        Thread.Sleep(500);
        var coinValue = altDriver.FindObject(By.PATH,"//GameController/GameView/Coin/CoinValueText");
        Assert.AreEqual("1", coinValue.GetText());
    }

```

Other notes
- tried to check if the issue occurs when the game window is fullscreen or not and 2 different displays, but it seems it doesn't matter
- the issue is reproducible on the released `2.0.2` version also

### ER
 
Should investigate if there is an issue with the test, and if the test is not the problem the expected result should be that: The player should jump and the test should pass all the time.

**Comment by RobertPoienar** [comment]
Triaged Week no. 5, 2024. Not prioritized for next releases.
