### ISSUE TITLE
RobotFramework library should be added under the Bindings folder

### ISSUE THREAD

**Issue by rucindrea** [alttester/AltTester-Unity-SDK#1496]
Now that we have the first Robot library ready, we should add in under the Bindings folder in the SDK repo.

**Comment by andreion1ca** [comment]
Because [this PR](https://github.com/alttester/AltTester-Unity-SDK/pull/1499)  fixes https://github.com/alttester/AltTester-Unity-SDK/issues/1496 and https://github.com/alttester/AltTester-Unity-SDK/issues/1497, I'll move this issue in `Testing`.

**Comment by iulianatodoran** [comment]
## Testing environment
- AltTester Unity SDK from `development` branch (12.02.2024)

## Tests performed
- ✅ Checked in the project repo that under the `Bindings~` folder there is the `AltTesterLibrary` for the `robot` framework 

  ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/42b25437-c0ff-4ab0-a324-e843573f8d87)

- Checked in the `robot` folder that:
  - ✅ there is also a `README.md` file with useful information for installing the library and how to import it inside projects
  - ✅ all the scripts contain the Copyright information
  - ✅ all the files are well structured and organized
  - ✅ the current released version is used (`2.0.3`)
  - ✅ in the AltDriver initialization from `AltTesterKeywords.py` the order of the parameters is the one required in https://github.com/alttester/AltTester-Unity-SDK/issues/1502 

## Conclusion
Considering the above information **I will close this ticket and move it into `Done`**.
