### ISSUE TITLE
Create a step in the pipeline to run the Robot tests

### ISSUE THREAD

**Issue by rucindrea** [alttester/AltTester-Unity-SDK#1497]
Once the robot library is added, we need to create a pipeline step that runs all the tests that are under the tests folder in the library . 

This can be done once #1496 is done.

**Comment by MihaiCuc98** [comment]
### Testing setup:
- Windows 10
- robot Bindings
- sampleScenes standalone instrumented with the latest dev SDK(12.02.2024)
- AltTesterDesktop 8a388d4

### Checks:
✔ Checked if the `Initialize Altdriver` has the concurrency tags available
✔ Checked if the `NoAppConnected`  error is triggered when running tests for unexisting apps (based on tags)
✔ Checked if the `ConnectionTimeoutError` is triggered when the connection data doesn't match
✔ Checked if the tests can be run on several devices if no tags were set
✔ Checked if the test can be run on reveal devices based on tags (checked with all tags)

No issues were found, I will close this issue.

**Comment by MihaiCuc98** [comment]
considering that the robot test run successfully on https://github.com/alttester/AltTester-Unity-SDK/actions/runs/7869518529/job/21469608383, I will close this ticket.
