### ISSUE TITLE
Add support for running tests concurrently with Robot framework

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1501]

**Comment by MihaiCuc98** [comment]
### Testing setup:
- Windows 10
- robot Bindings
- sampleScenes standalone instrumented with the latest dev SDK(12.02.2024)
- AltTesterDesktop 8a388d4

### Checks:
✔ Checked if the `Initialize Altdriver` has the concurrency tags available
✔ Checked if the `NoAppConnected`  error is triggered when running tests for unexisting apps (based on tags)
✔ Checked if the `ConnectionTimeoutError` is triggered when the connection data doesn't match
✔ Checked if the tests can be run on several devices if no tags were set
✔ Checked if the test can be run on reveal devices based on tags (checked with all tags)

No issues were found, I will close this issue.
