### ISSUE TITLE
[Bindings] Make AltDriver constructor backwards compatible with previous version of SDK

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1502]
Before we had: `host, port, app_name, enable_logging, timeout`

And now we have: `host, port, enable_logging, timeout, app_name, platform, platform version, device_instance_id, app_id`

We just need to put `app_name` after port like it was in the past

**Comment by iulianatodoran** [comment]
## Testing environment
- AltTester Unity SDK from `development` branch (12.02.2024)
- AltTester Desktop from `development` branch 

## Tests performed
- ✅ Checked in `AltDriver.cs` file and the `altdriver.py` that the order of parameters is the expected one
- ✅ Checked in a test that by using the former order for params without specifying to what param the value is assigned (eg. `altDriver = new AltDriver("192.168.1.105", 13000, true, "__default__")`) the syntax is not accepted in the compiler and the test cannot connect successfully for a build using an older SDK (eg. v `2.0.2`)
- ✅Checked in https://github.com/alttester/AltTester-Unity-SDK/issues/1496 that the expected order of params is used for `robot` framework 
- ✅ Checked in a test that by using the new order for params without specifying to what param the value is assigned (eg. `altDriver = new AltDriver("192.168.1.105", 13000, "__default__", true)`) the test can connect successfully for a build using an older SDK (eg. v `2.0.2`)
-  Checked if in the documentation on the API section the new order is applied in the params list, **BUT** there was no update made there, therefore opened another ticket https://github.com/alttester/AltTester-Unity-SDK/issues/1505

## Issue found during testing
- https://github.com/alttester/AltTester-Unity-SDK/issues/1505

## Conclusion
Considering the above information **I will move this ticket into `Done`**.
