### ISSUE TITLE
Update `AltDriver.Tests.csproj` with a newer version for the `Microsoft.NET.Test.Sdk` package

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1511]
## Description
 
As the example project has already a configuration for running .NET tests it would be useful to update in the `AltDriver.Tests.csproj` repo file the version used for `Microsoft.NET.Test.Sdk` package from `16.8.3` to `17.9.0` in order to be able to run tests in multiple threads with no issues

**Comment by MihaiCuc98** [comment]
### Setup:
- Windows 10
- AltTester-Unity-SDK project 49cd4f9b926cc0bd46c9ca1b302cba4ea4d7cccd
- AltTester Desktop 

### Checks:
✔ Checked if the dotnet tests are successfully run with the updated package.

Closing this issue.
