### ISSUE TITLE
Modify connection logic in game to not check every frame

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1516]
I modified the connection from checking every frame the status of communicationConnection( the websocket connection that handles the commands) and LiveUpdateConnection to events that the websocket triggers (connect and disconnect). This way I'm hoping to eliminate the disconnections problems.

**Comment by iulianatodoran** [comment]
There are still connection issues so I will close this ticket as for the current problems there are other tickets WIP.
