### ISSUE TITLE
Add a flag when OnClosed is connected to not rely on IsAlive

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1535]
In this, I will make the modification that will fix the problems with unresponsiveness for 5 min in the Desktop App.

This will be tested together with the ticket in Desktop

**Comment by iulianatodoran** [comment]
Waiting for https://github.com/alttester/AltTester-Desktop/issues/1502 to be merged

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Desktop/issues/1502 and related to the test running, ✅ checked that when running tests on multiple devices there are no connection issues for the test drivers.

Considering this, **I will move this ticket to `Done`.**
