### ISSUE TITLE
Fix wait_for_component_property method in Python and C#

### ISSUE THREAD

**Issue by rucindrea** [alttester/AltTester-Unity-SDK#1541]
In Python, the wait_for_component_property method always returned "property not found" instead of seperate exception for that, component not found and value not correct.

In C#, null values would produce a null reference exception.

**Comment by gomboskriszta15** [comment]
Tested:
C#:
- WaitForComponentProperty with correct arguments
- WaitForComponentProperty component not found
- WaitForComponentProperty property not found
- - WaitForComponentProperty assembly not found
- WaitForComponentProperty with time out
-Python:
same
