### ISSUE TITLE
Change AltServer to AltTester Server and add link

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1547]
Check all messages that we display and change the naming of the server where it appears.
For the error message: "Multiple apps detected" add a link pointing to the pricing page.
Also check in docs.

**Comment by iulianatodoran** [comment]
## Testing environment
- sampleGame build instrumented with AltTester Unity SDK v 2.1.0 from `development` branch (01.04.2024)
- AltTester Desktop from `development` branch  (01.04.24 - commit https://github.com/alttester/AltTester-Desktop/commit/bd00383a43d22c6a223fce6d6831ffe9061d43de)

## Tests performed and results
- ✅ Checked in the repo that the `AltServer` is changed to `AltTester®️ Server` in all relevant places :
- ✅ Checked in the repo that the `AltTester` is changed to `AltTester®️` in all places that weren't changed before
- ✅ Checked in the AltTester®️ Editor window and the Unity menu that the `®️` symbol  is added in all necessary places
- ✅ Checked in the documentation that the `AltServer` is changed to `AltTester®️ Server` and  `AltTester` is changed to `AltTester®️ in all relevant places that weren't changed before 
  - ❌ some screenshots are not updated but another ticket will be opened to address it as this is not a priority for the current WIP release (will be fixed after the release)

## Testing notes
- the link mentioned in the ticket could not be verified yet and the change needs to be made on the AltTester Server project and will be checked when testing https://github.com/alttester/AltServer/issues/83 

## Conclusion
Considering the above information **I will move this ticket to `Done`**.
