### ISSUE TITLE
Change connection logic in driver to wait to get notification that driver registered

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1551]
**Describe the feature/enhancement**

(Please describe your feature/enhancement idea)

**What is the reason you need this feature?**

(Offer us some context about how you will use this feature or why you this enhancement)

(Select which label is suitable for your issue)
/label ~feature  /label ~enhancement

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Desktop/issues/1484 

**Moving this ticket to `Done`.**
