### ISSUE TITLE
[Docs] Update Useful Links section

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1556]
Add PyPi Robot: https://pypi.org/project/alttester-robotframework-library/0.0.1/
Add different names to the 2 PyPi links.

**Comment by iulianatodoran** [comment]
Waiting for https://github.com/alttester/AltTester-Desktop/issues/1553

**Comment by gomboskriszta15** [comment]
Tested on staging that PyPi Python and Robot appear and they take you to the proper site.
