### ISSUE TITLE
Add "Delete Player Pref Key" missing example / test for robot library and documentation

### ISSUE THREAD

**Issue by melinda-nagy** [alttester/AltTester-Unity-SDK#1574]
ToDo: Add ROBOT missing test example and API doc for "Delete Player Pref Key" keyword.

PR1: https://github.com/alttester/AltTester-Unity-SDK/pull/1576
PR2: https://github.com/alttester/AltTester-Unity-SDK/pull/1588 - formatting issue

**Comment by iulianatodoran** [comment]
Re-opening the ticket as there is a formatting issue 
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/d47447cb-5086-4cdf-b666-63ad651c6a60)

**Comment by iulianatodoran** [comment]
✅ Checjed on the Live docs that the missing example is added properly with complete information and no layout issues

Considering this, **I will move the ticket to `Done`**.
