### ISSUE TITLE
Modify the UI of the AltDialog

### ISSUE THREAD

**Issue by andreion1ca** [alttester/AltTester-Unity-SDK#1583]
**Describe the feature/enhancement**
Change the UI of the AltDialog to contain a Cloud Server tab that can be used to connect to the AltTester-Cloud-Server. 

Concept: https://www.canva.com/design/DAGDalCssUk/qCnkS5blOJI8fKahULiRlQ/edit?utm_content=DAGDalCssUk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**What is the reason you need this feature?**
Because users should have a license key in order to use the Cloud Server, we should also modify the UI of the AltDialog.

**Additional info**
The issue for logic implementation of the Cloud tab: https://github.com/alttester/AltTester-Unity-SDK/issues/1424

**Comment by andreion1ca** [comment]
We can add this feature in Release 2.1.1 if we lock the Cloud Tab. Adding 2.1.1 label.

**Comment by iulianatodoran** [comment]
Tested with the latest version of SDK from the `development` branch and there is an issue for all tested platforms (Standalone Windows, Android, iOS, WebGL): 
:x: The `Driver connected` message is still displayed in the green popup after disconnecting the Desktop app from the `Disconnect` button

Considering this, **I will reopen the ticket**.
