### ISSUE TITLE
Add optional flag to WaitForComponentProperty [C# and Java]

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1605]
- boolean flag to indicate weather the component property should be taken as a string or not
-  also modify the docs (will do in another ticket)

**Comment by iulianatodoran** [comment]
Waiting for https://github.com/alttester/AltTester-Desktop/issues/1365 to be merged to test with AltTester desktop.

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Desktop/issues/1365.

**Moving the ticket to `Done`.**
