### ISSUE TITLE
Add optional flag to WaitForComponentProperty [Python and Robot]

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1613]
Continuing the work on https://github.com/alttester/AltTester-Unity-SDK/pull/1612

**Comment by iulianatodoran** [comment]
Waiting for https://github.com/alttester/AltTester-Desktop/issues/1365 to be merged to test with AltTester desktop.

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Desktop/issues/1365.

**Moving the ticket to `Done`.**
