### ISSUE TITLE
Update Copyright text to be 2024

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1618]

**Comment by iulianatodoran** [comment]
Some places still require the Copyright year to be updated:
-` \Bindings~\dotnet\AltDriver.Tests\unit\TestAltBaseCommand.cs` > update from `2023` to `2024`
- `LICENSE` > Update from `2022` to `2024`

Considering this, **I will reopen the ticket**.

**Comment by iulianatodoran** [comment]
✅ Chcked in the project repo and the Copyright text is updated for 2024, as expected with no other issues.

Considering the above information, **I will move this ticket to `Done`.**
