### ISSUE TITLE
Add information in docs how to make Lean Touch work with AltTester using Old Input System

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1620]

**Comment by iulianatodoran** [comment]
✅ Checked in the Staging documentation that in the FAQs section there is an entry with the necessary information with no typos or layout issuesvfor the workaround possible for users having trouble with AltTester in the Lean Touch demo package from Unity.

Considering the above information, **I will move this ticket to `Done`.**
