### ISSUE TITLE
Update documentation for the WaitForComponentProperty command

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1623]

**Comment by iulianatodoran** [comment]
✅ Checked on the Staging docs that:
- ✔️ the new parameter `getPropertyAsString` for the `WaitForComponentProperty` command is added properly in the _Parameters_ table with correct and complete information and with no typos or layout issues
- ✔️ examples for all languages are added properly that include the new parameter, with correct and complete information and with no typos or layout issues

Considering the above information, **I will move this ticket to `Done`.**
