### ISSUE TITLE
Move path validation to Server

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1631]

**Comment by iulianatodoran** [comment]
Waiting for the update from the Desktop from https://github.com/alttester/AltTester-Desktop/issues/1663

**Comment by iulianatodoran** [comment]
Another fix was made in https://github.com/alttester/AltTester-Unity-SDK/pull/1658

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltServer/issues/102.

Considering the above information, **I will move this ticket to `Done`.**
