### ISSUE TITLE
[Documentation] Update home page

### ISSUE THREAD

**Issue by ReichEdvin** [alttester/AltTester-Unity-SDK#1633]
Update documentation home page

## Description
1. Add a button for Return to website
2. Add to sidebar, at Usefeul links link to AltTester Blog page
3. Add a Home button, before AltTester Unity SDK and AltTester Desktop
4. When the user is on home page, the displayed name should be AltTester, now the last selected is displayed (SDK or Desktop)

**Comment by iulianatodoran** [comment]
## Testing Environment
- Staging documentation
- browsers: Chrome (Windows/ MacOS), Firefox (Windows/ Linux), Edge (Windows), Safari (MacOS)

## Checks
- ✅ Checked that from all sections of the documentation there is the possibility to return to the website through a button with the text `Return to website`
- ✅ Checked that the above button is functional and redirects to the staging website
- ✅ Checked that on the sidebar in _Useful Links_ there is new entry added for _AltTester Blog_ which is functional an redirects to the expected page
- ✅ Checked that there is a _Home Page_ link added before the _AltTester® Unity SDK_ and _AltTester® Desktop_ sections that redirects to the `index.html` page with the name _AltTester®_
- ✅ Checked that the additions are well integrated, with no issues created among the existing sections or other UI issues or missing sections
- ✅ Checked that the redirection from the Desktpp docs to the SDK docs is the expected one (except the known issue with the SDK docs versions that are not available only before release)
- ✅ Checked that the usefathom added to the docs pages is functional

## Conclusion
Considering the above information, **I will move this ticket to `Done`.**
