### ISSUE TITLE
Add wrapper in Robot for enable_logging

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1636]
Related to https://github.com/alttester/AltTester-Unity-SDK/issues/1578

**Comment by iulianatodoran** [comment]
## Testing Environment
- game instrumented with AltTester Unity SDK v 2.1.1
- AltTester Unity SDK from the `development` branch - commit https://github.com/alttester/AltTester-Unity-SDK/commit/0d9362c6c52fb098c183cf67ab038ec3f9469695
- AltTester Desktop from the `development` branch - commit https://github.com/alttester/AltTester-Desktop/commit/d48e4cafbf9f2e64bc66b49081c8807bd3eab37b

## Checks
- ✅ Checked that when running a test and using the new command for enabling/ disabling the AltDriver logging, it affects as expected the logging from the `AltTester.log` in the project's root directory.
  - tried with different setups and also using the `enable_logging` parameter in the AltDriver initialization as well
- ✅ Checked in the AltTester Library for robot that the methods for enabling/ disabling the AltDriver logging have correct examples 
  - issue found: ❌  there is a syntax issue in the examples that will be handled in another ticket 

## Conclusion
Considering the above information, **I will move this ticket to `Done`.**
