### ISSUE TITLE
Generating MessageId is not thread-safe manner

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1659]
It is possible to generate the same messageId on two different commands which cause bad responses
### AR
 
Two messageId are identical

## Expected result

Every messageId is unique

**Comment by iulianatodoran** [comment]
Moving this ticket to `Done` as we cannot reproduce it and already sent the solution to the users that had it to have a check, and if it will still be reproducible we will re-open it if the case.
