### ISSUE TITLE
"AltTester Input" text is not visible in altTester Dialog

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1674]

**Comment by gomboskriszta15** [comment]
Checked that:
1. AltTester Input is visible in the popup

![image](https://github.com/user-attachments/assets/5df13639-b70a-41f9-abe5-c3c5525e652b)

2. waitforcomponent in java for [], [[],[[]],[[]],[[]],[[]],[[],[],[]],[[[],[],[]]],[],[],[[]],[[]],[[]]] is working properly
