### ISSUE TITLE
[Intermittent] C# Driver Connection Can't Be Terminated from Desktop When Error Occurs During Connection

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1680]
An intermittent issue occurs where, after establishing a connection and checking with `GetServerVersion` to confirm the connection, a `NullReferenceException` is sometimes thrown. This issue seems to be related to threading. It's difficult to reproduce consistently, and attempts to debug via logs have not been successful. It appears that the `commandParam` might be set to null when trying to receive the server's response.

## Steps to reproduce
1. Connect to the app using the Desktop.
2. Attempt to reproduce the issue (though it happens unpredictably).

## Actual result
**AR:** Null Reference exception is thrown

## Expected result
**ER:** Connection is made and you can see the information of the app in the Desktop

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Desktop/issues/1803.

**Moving the ticket to `Done`**.
