### ISSUE TITLE
[FAQ] Update info about the oldest Unity version supported

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1685]
## Description
 
Currently we state in the FAQ section that the oldest Unity version supported is 2020.3, but on the Unity website it states that 2020.3 LTS stream has reached End-of-Support and we also have a limitation: the IL2CPP builds cannot be created using the Managed stripping level set to Minimal, as the Minimal level does not exist in Unity 2020 - as a consequence the users cannot connect their IL2CPP builds with the AltTester driver if the stripping level is higher. There are 2 options, either:
- We update the oldest supported version to 2021.3 LTS
- We add the info about the limitation for the IL2CPP builds when using Unity 2020.3 

## Additional info

The problem with the missing setting was reported by a user on Discord

**Comment by SiminaRe** [comment]
Tested on [stage](https://staging-alttesterdotcom-staging.kinsta.cloud/docs/sdk/latest/pages/faq-troubleshooting.html?highlight=faq) having latest commit [ae3f65e](https://github.com/alttester/alttester.com/commit/ae3f65e1930b53d64f23edc168dc3878b3c3d445).

Now, in FAQ, under _What versions of Unity does AltTester® Unity SDK work with?_ question, the following answer is displayed: 
_AltTester® Unity SDK works with Unity 2021.3 LTS or higher. We no longer support Unity 2020.3 LTS as it has reached its End-of-Support from Unity and there was also a limitation for the IL2CPP builds. If you encounter any issues we'd like to hear about them. You can [raise an issue](https://staging-alttesterdotcom-staging.kinsta.cloud/docs/sdk/latest/pages/contributing.html#did-you-find-a-bug) or join our community on [Discord](https://discord.gg/Ag9RSuS)._

Based on this, I will close this ticket.

Thank you!
