### ISSUE TITLE
PointerMoveHandler was not called when mouse is moved

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1688]
PointerMoveHandler should be called every frame in which mouse position/touch is different that the position in the previous frame

**Comment by iulianatodoran** [comment]
Waiting from @RobertPoienar for the SDK unity package for UI Toolkit to test this ticket.

**Comment by iulianatodoran** [comment]
See the comment from https://github.com/alttester/SDK-Packaging/issues/18. 

Re-opening the ticket.
