### ISSUE TITLE
Update first section in FAQ

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1691]
## Description
 
We need to update the info from the first section on FAQ section now that we have support for WebGL and Console. 

![image](https://github.com/user-attachments/assets/919e3baf-04f5-43a9-add5-bbfbfd8c1103)

**Comment by SiminaRe** [comment]
Tested on [stage](https://staging-alttesterdotcom-staging.kinsta.cloud/docs/sdk/latest/pages/faq-troubleshooting.html?highlight=faq) having latest commit [3bb68e](3bb68ebe457f96d456382c7f8730bc9fd65c1c56).

Now, in FAQ, under _On what platforms can I run tests with AltTester® Unity SDK?_ question, the following answer is displayed:
_PC, Mac, Android, iOS, WebGL, Console and Unity Editor._ 

Based on this, I will close this ticket.

Thank you!
