### ISSUE TITLE
New command and modification to support new UI

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1706]

**Comment by iulianatodoran** [comment]
Waiting for the fix from https://github.com/alttester/AltTester-Unity-SDK/pull/1710

**Comment by iulianatodoran** [comment]
Checked the Staging documentation for the newly inserted command, and everything is well integrated as expected with complete information, no layout, typos or missing information were found.

![image](https://github.com/user-attachments/assets/fa3a9857-ff1e-4408-8945-52f0e49a5e05)


Considering this, **I will move this ticket to `Done`**.
