### ISSUE TITLE
Modify from [Pro] to [Non-GPL] in documentation and fix link in GetVisualElementProperty

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1709]

**Comment by iulianatodoran** [comment]
Relatd ticket: https://github.com/alttester/AltTester-Unity-SDK/issues/1706

**Comment by iulianatodoran** [comment]
Tested in https://github.com/alttester/AltTester-Unity-SDK/issues/1706. 

Considering this, **I will move this ticket to `Done`**.
