### ISSUE TITLE
Update to v.2.2

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1712]
I updated everywhere in the sdk from 2.1.2 to 2.2.0 and modified check server version to throw a version if the instrumented build has a different version than 2.2.x or 1.0.x

**Comment by iulianatodoran** [comment]
This ticket waits for https://github.com/alttester/AltTester-Desktop/issues/1961

**Comment by iulianatodoran** [comment]
## Checks with the latest development version for SDK and Desktop
- ✅ Checked in the driver logs that when connecting the tests to an instrumented app having a different version than 2.2.0 or 1.1.0 (available for Unreal) there is a warning`Version mismatch. AltDriver version is {VERSION}. AltTester(R) version is {serverVersion}.`
- ✅ Checked that can connect and run successfully the tests for an instrumented app having a v 2.2.0 or v 1.1.0 (for Unreal checked by @andreion1ca) 
- ✅ Checked that the Desktop driver works with the latest major version of the tester and all of its minor versions > checked that the message is displayed where there is a version mismatch 
  - ✔️ version 2.2.0 works with Unity SDK 2.0.x - 2.2.x and Unreal SDK 1.0.x
  - ✔️ version 2.2.0 works with Unity SDK < 2.0.0 or Unity SDK 2.3.0 - the error for `Version mismatch...` is triggered
- ✅ version is updated in the green popup 
- ✅ version is updated in all necessary places in the repo
- ✅ version is updated in all necessary places on documentation
- ✅ other checks related to error messages and version compatibility/ incompatibility were performed in https://docs.google.com/spreadsheets/d/1oUf2F9KmY4OOjNsOQ4SQ4qj8_DmBEGbUVffYl5oX3UY/edit?gid=1779336891#gid=1779336891 

## Conclusion
Considering the above I will move the ticket to `Done`.
