### ISSUE TITLE
Docs fixes

### ISSUE THREAD

**Issue by andreion1ca** [alttester/AltTester-Unity-SDK#1717]

**Comment by iulianatodoran** [comment]
## Checksin the latest Staging documentation
- ✅ For Unreal SDK in Get Started > Set up the AltTester® Unreal SDK in your project > the Plugin screenshot ant title text contains the ®️ symbol
- ✅ For Unity SDK the _KeyDown_ command from _API > AltDriver > Input Actions > KeyDown_ has the power parameter not required 
- ✅ For Unity SDK the instrumented app screenshot from AltTester Editor > Build Settings has version updated to `2.2.0`

## Conclusion
Considering the above, **I will move the ticket to `Done`**.
