### ISSUE TITLE
Documentation Improvements on the waitForObject method

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1724]
## Description
Related to the issue on Desktop with the same title.

**Comment by gomboskriszta15** [comment]
https://github.com/alttester/AltTester-Unity-SDK/issues/1673 is also fixed in this PR

**Comment by iulianatodoran** [comment]
## Checks in the Staging documentation
- ✅ the comments from https://github.com/alttester/AltTester-Desktop/issues/1894#issuecomment-2437509317 are fixed for all `WaitForObject` methods and the information is visible and well integrated inside the documentation structure for both Unity and Unreal sections
- ✅ there are no typos, formatting, layout issues, or missing information in the changed areas

## Conclusion
The expected behaviors are achieved. Moving the ticket to `Done`.
