### ISSUE TITLE
Change method that uses reflection to have assembly as required parameters

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#925]
Change the following methods to have Assembly as required parameter:

- [ ] CallComponentMethod
- [ ] GetComponentMethod
- [ ] SetComponentMethod
- [ ] CallStaticMethod
- [ ] GetStaticMethod

**Comment by iulianatodoran** [comment]
### Testing Environment
- OS: Windows 10/ macOS Big Sur v 11.6.8/ Android 12/ iOS 12.5.5
- Unity v 2021.3.10f1 (Windows) and v 2021.3.5f1 (Mac)
- AltTester Unity SDK v 1.8.0 - latest from `development` branch in 19.10.22
- Staging documentation

### Tests performed and results
- :heavy_check_mark: Checked by running the automated tests for the SampleGame example that all pass on the platforms that were not tested on CI/CD: Windows, Android, and iOS
- :heavy_check_mark: Checked in the Staging documentation that the methods are updated in the API section and the examples that contain the mentioned methods in the ticket are also updated with the required parameter

### Conclusions
Closing the ticket.
