### ISSUE TITLE
[AWS cloud] Try solution from user for iproxy with aws issue and update documentation

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#927]
## Description
 
- Received from a user on discord a solution for the problem faced when using `iproxy` and `aws` for  integrating cloud testing using Appium, AltTester and Python with AWS stack. We should test it out and update the documentation afterwards.

## Additional info

- Here is the message from the user:
> I saw your message on the site that you had some troubles using iproxy and aws. I face the same problem, then I found that new format of iOS UDID (starting with iPhoneX) cause this issue.
> 
> The strange behaviour of AWS is that in the start script execution I see right value for device UDID: 00008030-000D04DE26F3802E, for example.
> Then in execution process this ID changed to 00008030000D04DE26F3802E (dash removed now).
> But the useful thing that AWS device has the right UDID as a name, so I changed iproxy -u switch value from DEVICEFARM_DEVICE_UDID_FOR_APPIUM to DEVICEFARM_DEVICE_NAME and it works.
> 
> Of course it's a strange and unstable (if Amazon developers decided to set devices names in another ways) but maybe it will be helpful for some other users and maybe for you.
> 
> UPD: Appium does not support dashes in device id's, so AWS remove dash for Appium and iproxy can't after that use udid in the right way.
> 
> UPD-2: Using just "iproxy 13000:13000" without -u switch also works great on AWS.

**Comment by sandraaltom** [comment]
Triaged Week no. 39, 2023. 
N/A since we don't user iproxy anymore. Closing this ticket.
