### ISSUE TITLE
Maven id changes

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#956]
com.altom -> com.alttester
changed id
took  changes from the PR from the ticket for Upgrade Guide

**Comment by iulianatodoran** [comment]
### Testing Environment
- OS: Windows 10/ macOS Big Sur v 11.6.8/ Android 12/ iOS 12.5.5
- Unity v 2021.3.10f1 (Windows) and v 2021.3.5f1 (Mac)
- AltTester Unity SDK v 1.8.0 - latest from `development` branch in 19.10.22
- Staging documentation

### Tests performed and results
- :heavy_check_mark: Checked by running the automated tests for the SampleGame example that all pass on the platforms that were not tested on CI/CD: Windows, Android, and iOS
- :heavy_check_mark: Checked in the Staging documentation that the id `com.altom` is changed to  `com.alttester` regarding maven repository

### Conclusions
Closing the ticket.
