### ISSUE TITLE
[Retro] Improve test automation coverage 

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#963]
Include tests that do not necessarily follow the happy flow.
Include testcases for different inputs.

**Comment by AlexMitDemBart** [comment]
I could improve the coverage for java.

**Comment by sandraaltom** [comment]
Two parts to be covered within this ticket: 

- [ ] run the current tests and if they fail update them according to the latest configurations
- [ ] add new tests for the parts that were added after the existing tests were created
