### ISSUE TITLE
New command: Reset Input

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#968]
I'm not sure what would we call this command but I want this command to reset all the inputs that are still active when this command is called. This means all coroutine, keys and touches should be cleared. 
I know this is doable with the old input system but might need to investigate if it is possible for NIS.

- [ ] Add logic on AltTester side
- [ ] Add command in C# Driver
- [ ] Add command in Java Driver
- [ ] Add command in Python Driver
- [ ] Add Tests for all 3 languages

**Comment by andreion1ca** [comment]
## Testing Environment

- OS: Windows 10
- Project: _**alttester-sample-projects/NIS--LeanTouch**_ instrumented with AltTester Unity SDK v.1.8.1

## Tests performed and results

✔️ Checked that the documentation for the ResetInput command is correct and the example works properly.
✔️  Checked using an automated test on a project with NewInputSystem, that the ResetInput command:
- ✔️ clear the key codes pressed
- ✔️ set the touch_count to 0
- ✔️ change the mouse position to (0, 0)
- ✔️ change acceleration to (0, 0, 0)

(Tests can be found in [this project](https://github.com/alttester-sample-projects/NIS--LeanTouch) in the _NewAltUnityTest.cs_ file)

## Conclusion
- Closing the ticket.
