### ISSUE TITLE
Fix AltTester Desktop version check regex

### ISSUE THREAD

**Issue by ReichEdvin** [alttester/AltTester-Unity-SDK#970]
## Steps to reproduce
Currently the regex that check the AltTester Desktop version doesn't check the version, only the download link.

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 10/ macOS Big Sur v 11.6.8
- Unity v 2021.3.13f1 (Windows) and v 2021.3.5f1 (Mac)

### Testes performed and results
- ✔️ Checked that when a new version of AltTester Desktop is released the popup for download is displayed with the correct information
- ✔️ Checked that the links in the popup all work and direct to the expected location/ triggers the download of the expected file
- ✔️ Checked that after closing the popup it is not displayed anymore until a new version is available for download 

### Note
For a display issue opened #1000 that was not triggered by the implementation for this ticket

### Conclusion
The purpose of this ticket was achieved
Closing the ticket.
