### ISSUE TITLE
Change name to AltTester for the new arhitecture

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#972]
Merge all modification from master to the feature proxy

**Comment by iulianatodoran** [comment]
Problems found:
- These files contain the old `AltUnity` name
![image](https://user-images.githubusercontent.com/62327834/202121355-9d77f030-61eb-4cb7-ae9d-3f6bba0c5715.png)

- These files use the `Alt `  name (with space)
![image](https://user-images.githubusercontent.com/62327834/202121816-cb9c765d-753d-426c-a35f-6faa57a2212e.png)
