### ISSUE TITLE
Enable WebGL

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#982]
## Description
Uncomment WebGL related code.

**Comment by gomboskriszta15** [comment]
#749 is also fixed here

**Comment by sandraaltom** [comment]
Once this ticket is fixed, @iulianatodoran you can also close https://github.com/alttester/AltTester-Unity-SDK/issues/749

**Comment by iulianatodoran** [comment]
### Notes on testing 
In 06.01.23 Tried to create WebGL builds and tested with AltTester Desktop (latest from `development` branch) for _TrashCat_ and _Goalkeeper_ games with the recommender LTS versions on Unity `2020.3.43f1`, `20201.3.16f1` and the latest `2022.2.1f1` and encountered problems **only for the 2022 builds**:
- ❗ in Desktop app the screenshot area does not render the screenshots and cannot select objects in Hierarchy to check their properties in the third column
  
  ![image](https://user-images.githubusercontent.com/62327834/211528132-3c99bb5b-9446-4ce5-b21b-95da4b0505bb.png)

- ❗ after connecting the Desktop app, the WebGL build freezes

Talked to @gomboskriszta15 to have a check on this.

### Other notes
@gomboskriszta15 informed me that the NIS is not compatible with the WebGL implementation so far so I could not test with NIS game builds. @sandraaltom we should discuss with the dev team how to handle further this aspect

**Comment by iulianatodoran** [comment]
For the issues mentioned in my previous comment, the two referenced tickets #1104 #1105 were opened. 

**In conclusion, will close this ticket.**
